

import copy
import pickle as PD
import libevdev as LD
from libevdev import InputEvent as IE


from datetime import datetime as DT
# from os import path as PATH
# import pprint as PP


# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# * copy a variable completely
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def copyVar(varIn):
	outVar = copy.deepcopy(varIn)
	return outVar


def pickleIt(fileName, dataToPickle):
	with open(fileName, 'wb') as FD_OUT_:
		PD.dump(dataToPickle, FD_OUT_)
		FD_OUT_.flush()
		FD_OUT_.close()


def unPickleIt(fileName):
	with open(fileName, "rb") as FD_IN_:
		dataToRTN_ = PD.load(FD_IN_)
	return dataToRTN_


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * start of constants.py cut 20200819.003108
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# common constants
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#


ABS_HAT0X = "ABS_HAT0X"
ABS_HAT0Y = "ABS_HAT0Y"
ABS_RZ = "ABS_RZ"
ABS_X = "ABS_X"
ABS_Y = "ABS_Y"
ABS_Z = "ABS_Z"


AXNAME = "AXNAME"
AXOUT = "AXOUT"


BIN32 = lambda X, Y: f"{X:032b}"
HEX16 = lambda X: f"{X:04H}"
HEX32 = lambda X: f"{X:08H}"
HEX64 = lambda X: f"{X:016H}"
HEX8 = lambda X: f"{X:02H}"


DEVICEABSSTATUS = "DEVICEABSSTATUS"
DEVICEBUTTONSSTATUS = "DEVICEBUTTONSSTATUS"
DEVICEENABLED = "DEVICEENABLED"
DEVICEERRORNEXTTIME = "DEVICEERRORNEXTTIME"
DEVICEERRORSTATUS = "DEVICEERRORSTATUS"
DEVICEFD = "DEVICEFD"
DEVICEIDNAME = "DEVICEIDNAME"
DEVICEKEYSTATUS = "DEVICEKEYSTATUS"
DEVICENAME = "DEVICENAME"
DEVICEPROFILE = "DEVICEPROFILE"
DEVICEQUEUE = "DEVICEQUEUE"
DEVICERELSTATUS = "DEVICERELSTATUS"
DEVICEREPEATING = "DEVICEREPEATING"
DEVICEREPEATNEXTTIME = "DEVICEREPEATNEXTTIME"
DEVICEREPEATNEXTTIMEDELTA = "DEVICEREPEATNEXTTIMEDELTA"
DEVICETYPE = "DEVICETYPE"


ABSDEADWIDTH = "ABSDEADWIDTH"
ABSMAX = "ABSMAX"
ABSMAXVAL = 0XFFFFFFFFFFFFFFFF
ABSMIN = "ABSMIN"
ABSMINVAL = -0XFFFFFFFFFFFFFFFF
ABSZERO = "ABSZERO"
ABSZEROVAL = 0X0000000000000000
HATMAX = 1
HATMID = 0
HATMIN = -1
JOYSTICKDEAD = 100
JOYSTICKMAX = 255
JOYSTICKMID = 128
JOYSTICKMIN = 0
KEYHLD = 0X02
KEYPRS = 0X01
KEYPRSHLD = 0X03
KEYRLS = 0X00
MOUSEDISTANCE = 1  # ow far to move the mouse per event
REL_DIAL = "REL_DIAL"
REL_HWHEEL = "REL_HWHEEL"
REL_HWHEEL_HI_RES = "REL_HWHEEL_HI_RES"
REL_WHEEL = "REL_WHEEL"
REL_WHEEL_HI_RES = "REL_WHEEL_HI_RES"
RELDN = "RELDN"
RELDNVAL = -1
RELUP = "RELUP"
RELUPVAL = 1
RELX = "RELX"
RELY = "RELY"
RELZERO = "RELZERO"
RELZEROVAL = 0
VALUE_S = "VALUE_S"
WHEELDISTANCE = 1  # how many clicks of the wheel per event
SYNREPORT = IE(LD.EV_SYN.SYN_REPORT, 0)


BUTTONSNOT = 0B00000000
BTNS00 = 0B00000001
BTNS05 = 0B00000010
BTNS06 = 0B00000100
BTNS07 = 0B00001000
BTNS08 = 0B00010000
BTNS22 = 0B00100000
BTNS23 = 0B01000000
BTNS24 = 0B10000000


DIRDN =      0B0100
DIRDNLT =    0B1100
DIRDNLTMSK = 0B0011
DIRDNMSK =   0B1011
DIRDNRT =    0B0110
DIRDNRTMSK = 0B1001
DIRLT =      0B1000
DIRLTMSK =   0B0111
DIRNOT =     0B0000
DIRNOTMSK =  0B1111
DIRRT =      0B0010
DIRRTMSK =   0B1101
DIRUP =      0B0001
DIRUPLT =    0B1001
DIRUPLTMSK = 0B0110
DIRUPMSK =   0B1110
DIRUPRT =    0B0011
DIRUPRTMSK = 0B1100


ERRORNOT = 0X00000000
REPEATNOT = 0X00000000


#  most mice don't have a held value for the buttons,
#  it is included here for completeness,
#  and faked for use when it does happen
MSEUP = IE(LD.EV_REL.REL_Y, -MOUSEDISTANCE)
MSEDN = IE(LD.EV_REL.REL_Y, MOUSEDISTANCE)
MSELT = IE(LD.EV_REL.REL_X, -MOUSEDISTANCE)
MSERT = IE(LD.EV_REL.REL_X, MOUSEDISTANCE)

MSEWHLUP = IE(LD.EV_REL.REL_WHEEL, WHEELDISTANCE)
MSEWHLDN = IE(LD.EV_REL.REL_WHEEL, -WHEELDISTANCE)
MSEWHLLT = IE(LD.EV_REL.REL_HWHEEL, -WHEELDISTANCE)
MSEWHLRT = IE(LD.EV_REL.REL_HWHEEL, WHEELDISTANCE)

MSEXTRABTNHLD = IE(LD.EV_KEY.BTN_EXTRA, KEYHLD)
MSEXTRABTNPRSD = IE(LD.EV_KEY.BTN_EXTRA, KEYPRS)
MSEXTRABTNPRSHLDD = IE(LD.EV_KEY.BTN_EXTRA, KEYPRSHLD)
MSEXTRABTNRLS = IE(LD.EV_KEY.BTN_EXTRA, KEYRLS)

MSEHRWHLUP = IE(LD.EV_REL.REL_WHEEL_HI_RES, WHEELDISTANCE)
MSEHRWHLDN = IE(LD.EV_REL.REL_WHEEL_HI_RES, -WHEELDISTANCE)
MSEHRWHLLT = IE(LD.EV_REL.REL_HWHEEL_HI_RES, -WHEELDISTANCE)
MSEHRWHLRT = IE(LD.EV_REL.REL_HWHEEL_HI_RES, WHEELDISTANCE)

MSELTBTNHLD = IE(LD.EV_KEY.BTN_LEFT, KEYHLD)
MSELTBTNPRSHLD = IE(LD.EV_KEY.BTN_LEFT, KEYPRSHLD)
MSELTBTNPRS = IE(LD.EV_KEY.BTN_LEFT, KEYPRS)
MSELTBTNRLS = IE(LD.EV_KEY.BTN_LEFT, KEYRLS)

MSEMIDBTNHLD = IE(LD.EV_KEY.BTN_MIDDLE, KEYHLD)
MSEMIDBTNPRS = IE(LD.EV_KEY.BTN_MIDDLE, KEYPRS)
MSEMIDBTNPRSHLD = IE(LD.EV_KEY.BTN_MIDDLE, KEYPRSHLD)
MSEMIDBTNRLS = IE(LD.EV_KEY.BTN_MIDDLE, KEYRLS)

MSERTBTNHLD = IE(LD.EV_KEY.BTN_RIGHT, KEYHLD)
MSERTBTNPRS = IE(LD.EV_KEY.BTN_RIGHT, KEYPRS)
MSERTBTNPRSHLD = IE(LD.EV_KEY.BTN_RIGHT, KEYPRSHLD)
MSERTBTNRLS = IE(LD.EV_KEY.BTN_RIGHT, KEYRLS)

MSESIDEBTNHLD = IE(LD.EV_KEY.BTN_SIDE, KEYHLD)
MSESIDEBTNPS = IE(LD.EV_KEY.BTN_SIDE, KEYPRS)
MSESIDEBTNPRSHLD = IE(LD.EV_KEY.BTN_SIDE, KEYPRSHLD)
MSESIDEBTNRLS = IE(LD.EV_KEY.BTN_SIDE, KEYRLS)

MSEFWDBTNHLD = IE(LD.EV_KEY.BTN_FORWARD, KEYHLD)
MSEFWDBTNPS = IE(LD.EV_KEY.BTN_FORWARD, KEYPRS)
MSEFWDBTNPRSHLD = IE(LD.EV_KEY.BTN_FORWARD, KEYPRSHLD)
MSEFWDBTNRLS = IE(LD.EV_KEY.BTN_FORWARD, KEYRLS)

MSEBAKBTNHLD = IE(LD.EV_KEY.BTN_BAK, KEYHLD)
MSEBAKBTNPS = IE(LD.EV_KEY.BTN_BAK, KEYPRS)
MSEBAKBTNPRSHLD = IE(LD.EV_KEY.BTN_BAK, KEYPRSHLD)
MSEBAKBTNRLS = IE(LD.EV_KEY.BTN_BAK, KEYRLS)

MSETASKBTNHLD = IE(LD.EV_KEY.BTN_TASK, KEYHLD)
MSETASKBTNPS = IE(LD.EV_KEY.BTN_TASK, KEYPRS)
MSETASKBTNPRSHLD = IE(LD.EV_KEY.BTN_TASK, KEYPRSHLD)
MSETASKBTNRLS = IE(LD.EV_KEY.BTN_TASK, KEYRLS)


# I generally do my own held key tracking as some keyboards don't support them, and sending them is less than effective,
# so think of these as reserved for possible future use
KBD0HLD = IE(LD.EV_KEY.KEY_0, KEYHLD)
KBD0PRS = IE(LD.EV_KEY.KEY_0, KEYPRS)
KBD0RLS = IE(LD.EV_KEY.KEY_0, KEYRLS)

KBD102HLD = IE(LD.EV_KEY.KEY_102ND, KEYHLD)
KBD102PRS = IE(LD.EV_KEY.KEY_102ND, KEYPRS)
KBD102RLS = IE(LD.EV_KEY.KEY_102ND, KEYRLS)

KBD1HLD = IE(LD.EV_KEY.KEY_1, KEYHLD)
KBD1PRS = IE(LD.EV_KEY.KEY_1, KEYPRS)
KBD1RLS = IE(LD.EV_KEY.KEY_1, KEYRLS)

KBD2HLD = IE(LD.EV_KEY.KEY_2, KEYHLD)
KBD2PRS = IE(LD.EV_KEY.KEY_2, KEYPRS)
KBD2RLS = IE(LD.EV_KEY.KEY_2, KEYRLS)

KBD3HLD = IE(LD.EV_KEY.KEY_3, KEYHLD)
KBD3PRS = IE(LD.EV_KEY.KEY_3, KEYPRS)
KBD3RLS = IE(LD.EV_KEY.KEY_3, KEYRLS)

KBD4HLD = IE(LD.EV_KEY.KEY_4, KEYHLD)
KBD4PRS = IE(LD.EV_KEY.KEY_4, KEYPRS)
KBD4RLS = IE(LD.EV_KEY.KEY_4, KEYRLS)

KBD5HLD = IE(LD.EV_KEY.KEY_5, KEYHLD)
KBD5PRS = IE(LD.EV_KEY.KEY_5, KEYPRS)
KBD5RLS = IE(LD.EV_KEY.KEY_5, KEYRLS)

KBD6HLD = IE(LD.EV_KEY.KEY_6, KEYHLD)
KBD6PRS = IE(LD.EV_KEY.KEY_6, KEYPRS)
KBD6RLS = IE(LD.EV_KEY.KEY_6, KEYRLS)

KBD7HLD = IE(LD.EV_KEY.KEY_7, KEYHLD)
KBD7PRS = IE(LD.EV_KEY.KEY_7, KEYPRS)
KBD7RLS = IE(LD.EV_KEY.KEY_7, KEYRLS)

KBD8HLD = IE(LD.EV_KEY.KEY_8, KEYHLD)
KBD8PRS = IE(LD.EV_KEY.KEY_8, KEYPRS)
KBD8RLS = IE(LD.EV_KEY.KEY_8, KEYRLS)

KBD9HLD = IE(LD.EV_KEY.KEY_9, KEYHLD)
KBD9PRS = IE(LD.EV_KEY.KEY_9, KEYPRS)
KBD9RLS = IE(LD.EV_KEY.KEY_9, KEYRLS)

KBDAHLD = IE(LD.EV_KEY.KEY_A, KEYHLD)
KBDAPRS = IE(LD.EV_KEY.KEY_A, KEYPRS)
KBDARLS = IE(LD.EV_KEY.KEY_A, KEYRLS)

KBDAGAINHLD = IE(LD.EV_KEY.KEY_AGAIN, KEYHLD)
KBDAGAINPRS = IE(LD.EV_KEY.KEY_AGAIN, KEYPRS)
KBDAGAINRLS = IE(LD.EV_KEY.KEY_AGAIN, KEYRLS)

KBDALTLHLD = IE(LD.EV_KEY.KEY_LEFTALT, KEYHLD)
KBDALTLPRS = IE(LD.EV_KEY.KEY_LEFTALT, KEYPRS)
KBDALTLRLS = IE(LD.EV_KEY.KEY_LEFTALT, KEYRLS)

KBDAPOSTOPHEHLD = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYHLD)
KBDAPOSTOPHEPRS = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYPRS)
KBDAPOSTOPHERLS = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYRLS)

KBDBHLD = IE(LD.EV_KEY.KEY_B, KEYHLD)
KBDBPRS = IE(LD.EV_KEY.KEY_B, KEYPRS)
KBDBRLS = IE(LD.EV_KEY.KEY_B, KEYRLS)

KBDBKHLD = IE(LD.EV_KEY.KEY_BACK, KEYHLD)
KBDBKPRS = IE(LD.EV_KEY.KEY_BACK, KEYPRS)
KBDBKRLS = IE(LD.EV_KEY.KEY_BACK, KEYRLS)

KBDBKSLASHHLD = IE(LD.EV_KEY.KEY_BACKSLASH, KEYHLD)
KBDBKSLASHRRESSED = IE(LD.EV_KEY.KEY_BACKSLASH, KEYRLS)
KBDBKSLASHPELEASED = IE(LD.EV_KEY.KEY_BACKSLASH, KEYPRS)

KBDBKSPCHLD = IE(LD.EV_KEY.KEY_BACKSPACE, KEYHLD)
KBDBKSPCPRS = IE(LD.EV_KEY.KEY_BACKSPACE, KEYPRS)
KBDBKSPCRLS = IE(LD.EV_KEY.KEY_BACKSPACE, KEYRLS)

KBDCALCHLD = IE(LD.EV_KEY.KEY_CALC, KEYHLD)
KBDCALCPRS = IE(LD.EV_KEY.KEY_CALC, KEYPRS)
KBDCALCRLS = IE(LD.EV_KEY.KEY_CALC, KEYRLS)

KBDCAPSLKHLD = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYHLD)
KBDCAPSLKPRS = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYPRS)
KBDCAPSLKRLS = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYRLS)

KBDCHLD = IE(LD.EV_KEY.KEY_C, KEYHLD)
KBDCPRS = IE(LD.EV_KEY.KEY_C, KEYPRS)
KBDCRLS = IE(LD.EV_KEY.KEY_C, KEYRLS)

KBDCOFFEEHLD = IE(LD.EV_KEY.KEY_COFFEE, KEYHLD)
KBDCOFFEEPRS = IE(LD.EV_KEY.KEY_COFFEE, KEYPRS)
KBDCOFFEERLS = IE(LD.EV_KEY.KEY_COFFEE, KEYRLS)

KBDCOMMAHLD = IE(LD.EV_KEY.KEY_COMMA, KEYHLD)
KBDCOMMAPRS = IE(LD.EV_KEY.KEY_COMMA, KEYPRS)
KBDCOMMARLS = IE(LD.EV_KEY.KEY_COMMA, KEYRLS)

KBDCOMPOSEHLD = IE(LD.EV_KEY.KEY_COMPOSE, KEYHLD)
KBDCOMPOSEPRS = IE(LD.EV_KEY.KEY_COMPOSE, KEYPRS)
KBDCOMPOSERLS = IE(LD.EV_KEY.KEY_COMPOSE, KEYRLS)

KBDCOPYHLD = IE(LD.EV_KEY.KEY_COPY, KEYHLD)
KBDCOPYPRS = IE(LD.EV_KEY.KEY_COPY, KEYPRS)
KBDCOPYRLS = IE(LD.EV_KEY.KEY_COPY, KEYRLS)

KBDCUTHLD = IE(LD.EV_KEY.KEY_CUT, KEYHLD)
KBDCUTPRS = IE(LD.EV_KEY.KEY_CUT, KEYPRS)
KBDCUTRLS = IE(LD.EV_KEY.KEY_CUT, KEYRLS)

KBDDHLD = IE(LD.EV_KEY.KEY_D, KEYHLD)
KBDDPRS = IE(LD.EV_KEY.KEY_D, KEYPRS)
KBDDRLS = IE(LD.EV_KEY.KEY_D, KEYRLS)

KBDDELHLD = IE(LD.EV_KEY.KEY_DELETE, KEYHLD)
KBDDELPRS = IE(LD.EV_KEY.KEY_DELETE, KEYPRS)
KBDDELRLS = IE(LD.EV_KEY.KEY_DELETE, KEYRLS)

KBDDOTHLD = IE(LD.EV_KEY.KEY_DOT, KEYHLD)
KBDDOTPRS = IE(LD.EV_KEY.KEY_DOT, KEYPRS)
KBDDOTRLS = IE(LD.EV_KEY.KEY_DOT, KEYRLS)

KBDDNHLD = IE(LD.EV_KEY.KEY_DOWN, KEYHLD)
KBDDNPRS = IE(LD.EV_KEY.KEY_DOWN, KEYPRS)
KBDDNRLS = IE(LD.EV_KEY.KEY_DOWN, KEYRLS)

KBDEHLD = IE(LD.EV_KEY.KEY_E, KEYHLD)
KBDEPRS = IE(LD.EV_KEY.KEY_E, KEYPRS)
KBDERLS = IE(LD.EV_KEY.KEY_E, KEYRLS)

KBDEDITHLD = IE(LD.EV_KEY.KEY_EDIT, KEYHLD)
KBDEDITPRS = IE(LD.EV_KEY.KEY_EDIT, KEYPRS)
KBDEDITRLS = IE(LD.EV_KEY.KEY_EDIT, KEYRLS)

KBDEJECTCDHLD = IE(LD.EV_KEY.KEY_EJECTCD, KEYHLD)
KBDEJECTCDPRS = IE(LD.EV_KEY.KEY_EJECTCD, KEYPRS)
KBDEJECTCDRLS = IE(LD.EV_KEY.KEY_EJECTCD, KEYRLS)

KBDENDHLD = IE(LD.EV_KEY.KEY_END, KEYHLD)
KBDENDPRS = IE(LD.EV_KEY.KEY_END, KEYPRS)
KBDENDRLS = IE(LD.EV_KEY.KEY_END, KEYRLS)

KBDENTERHLD = IE(LD.EV_KEY.KEY_ENTER, KEYHLD)
KBDENTERPRS = IE(LD.EV_KEY.KEY_ENTER, KEYPRS)
KBDENTERRLS = IE(LD.EV_KEY.KEY_ENTER, KEYRLS)

KBDEQHLD = IE(LD.EV_KEY.KEY_EQUAL, KEYHLD)
KBDEQPRS = IE(LD.EV_KEY.KEY_EQUAL, KEYPRS)
KBDEQRLS = IE(LD.EV_KEY.KEY_EQUAL, KEYRLS)

KBDESCHLD = IE(LD.EV_KEY.KEY_ESC, KEYHLD)
KBDESCPRS = IE(LD.EV_KEY.KEY_ESC, KEYPRS)
KBDESCRLS = IE(LD.EV_KEY.KEY_ESC, KEYRLS)

KBDF1HLD = IE(LD.EV_KEY.KEY_F1, KEYHLD)
KBDF1PRS = IE(LD.EV_KEY.KEY_F1, KEYPRS)
KBDF1RLS = IE(LD.EV_KEY.KEY_F1, KEYRLS)

KBDF2HLD = IE(LD.EV_KEY.KEY_F2, KEYHLD)
KBDF2PRS = IE(LD.EV_KEY.KEY_F2, KEYPRS)
KBDF2RLS = IE(LD.EV_KEY.KEY_F2, KEYRLS)

KBDF3HLD = IE(LD.EV_KEY.KEY_F3, KEYHLD)
KBDF3PRS = IE(LD.EV_KEY.KEY_F3, KEYPRS)
KBDF3RLS = IE(LD.EV_KEY.KEY_F3, KEYRLS)

KBDF4HLD = IE(LD.EV_KEY.KEY_F4, KEYHLD)
KBDF4PRS = IE(LD.EV_KEY.KEY_F4, KEYPRS)
KBDF4RLS = IE(LD.EV_KEY.KEY_F4, KEYRLS)

KBDF5HLD = IE(LD.EV_KEY.KEY_F5, KEYHLD)
KBDF5PRS = IE(LD.EV_KEY.KEY_F5, KEYPRS)
KBDF5RLS = IE(LD.EV_KEY.KEY_F5, KEYRLS)

KBDF6HLD = IE(LD.EV_KEY.KEY_F6, KEYHLD)
KBDF6PRS = IE(LD.EV_KEY.KEY_F6, KEYPRS)
KBDF6RLS = IE(LD.EV_KEY.KEY_F6, KEYRLS)

KBDF7HLD = IE(LD.EV_KEY.KEY_F7, KEYHLD)
KBDF7PRS = IE(LD.EV_KEY.KEY_F7, KEYPRS)
KBDF7RLS = IE(LD.EV_KEY.KEY_F7, KEYRLS)

KBDF8HLD = IE(LD.EV_KEY.KEY_F8, KEYHLD)
KBDF8PRS = IE(LD.EV_KEY.KEY_F8, KEYPRS)
KBDF8RLS = IE(LD.EV_KEY.KEY_F8, KEYRLS)

KBDF9HLD = IE(LD.EV_KEY.KEY_F9, KEYHLD)
KBDF9PRS = IE(LD.EV_KEY.KEY_F9, KEYPRS)
KBDF9RLS = IE(LD.EV_KEY.KEY_F9, KEYRLS)

KBDF10HLD = IE(LD.EV_KEY.KEY_F10, KEYHLD)
KBDF10PRS = IE(LD.EV_KEY.KEY_F10, KEYPRS)
KBDF10RLS = IE(LD.EV_KEY.KEY_F10, KEYRLS)

KBDF11HLD = IE(LD.EV_KEY.KEY_F11, KEYHLD)
KBDF11PRS = IE(LD.EV_KEY.KEY_F11, KEYPRS)
KBDF11RLS = IE(LD.EV_KEY.KEY_F11, KEYRLS)

KBDF12HLD = IE(LD.EV_KEY.KEY_F12, KEYHLD)
KBDF12PRS = IE(LD.EV_KEY.KEY_F12, KEYPRS)
KBDF12RLS = IE(LD.EV_KEY.KEY_F12, KEYRLS)

KBDF13HLD = IE(LD.EV_KEY.KEY_F13, KEYHLD)
KBDF13PRS = IE(LD.EV_KEY.KEY_F13, KEYPRS)
KBDF13RLS = IE(LD.EV_KEY.KEY_F13, KEYRLS)

KBDF14HLD = IE(LD.EV_KEY.KEY_F14, KEYHLD)
KBDF14PRS = IE(LD.EV_KEY.KEY_F14, KEYPRS)
KBDF14RLS = IE(LD.EV_KEY.KEY_F14, KEYRLS)

KBDF15HLD = IE(LD.EV_KEY.KEY_F15, KEYHLD)
KBDF15PRS = IE(LD.EV_KEY.KEY_F15, KEYPRS)
KBDF15RLS = IE(LD.EV_KEY.KEY_F15, KEYRLS)

KBDF16HLD = IE(LD.EV_KEY.KEY_F16, KEYHLD)
KBDF16PRS = IE(LD.EV_KEY.KEY_F16, KEYPRS)
KBDF16RLS = IE(LD.EV_KEY.KEY_F16, KEYRLS)

KBDF17HLD = IE(LD.EV_KEY.KEY_F17, KEYHLD)
KBDF17PRS = IE(LD.EV_KEY.KEY_F17, KEYPRS)
KBDF17RLS = IE(LD.EV_KEY.KEY_F17, KEYRLS)

KBDF18HLD = IE(LD.EV_KEY.KEY_F18, KEYHLD)
KBDF18PRS = IE(LD.EV_KEY.KEY_F18, KEYPRS)
KBDF18RLS = IE(LD.EV_KEY.KEY_F18, KEYRLS)

KBDF19HLD = IE(LD.EV_KEY.KEY_F19, KEYHLD)
KBDF19PRS = IE(LD.EV_KEY.KEY_F19, KEYPRS)
KBDF19RLS = IE(LD.EV_KEY.KEY_F19, KEYRLS)

KBDF20HLD = IE(LD.EV_KEY.KEY_F20, KEYHLD)
KBDF20PRS = IE(LD.EV_KEY.KEY_F20, KEYPRS)
KBDF20RLS = IE(LD.EV_KEY.KEY_F20, KEYRLS)

KBDF21HLD = IE(LD.EV_KEY.KEY_F21, KEYHLD)
KBDF21PRS = IE(LD.EV_KEY.KEY_F21, KEYPRS)
KBDF21RLS = IE(LD.EV_KEY.KEY_F21, KEYRLS)

KBDF22HLD = IE(LD.EV_KEY.KEY_F22, KEYHLD)
KBDF22PRS = IE(LD.EV_KEY.KEY_F22, KEYPRS)
KBDF22RLS = IE(LD.EV_KEY.KEY_F22, KEYRLS)

KBDF23HLD = IE(LD.EV_KEY.KEY_F23, KEYHLD)
KBDF23PRS = IE(LD.EV_KEY.KEY_F23, KEYPRS)
KBDF23RLS = IE(LD.EV_KEY.KEY_F23, KEYRLS)

KBDF24HLD = IE(LD.EV_KEY.KEY_F24, KEYHLD)
KBDF24PRS = IE(LD.EV_KEY.KEY_F24, KEYPRS)
KBDF24RLS = IE(LD.EV_KEY.KEY_F24, KEYRLS)

KBDFHLD = IE(LD.EV_KEY.KEY_F, KEYHLD)
KBDFPRS = IE(LD.EV_KEY.KEY_F, KEYPRS)
KBDFRLS = IE(LD.EV_KEY.KEY_F, KEYRLS)

KBDFINDHLD = IE(LD.EV_KEY.KEY_FIND, KEYHLD)
KBDFINDPRS = IE(LD.EV_KEY.KEY_FIND, KEYPRS)
KBDFINDRLS = IE(LD.EV_KEY.KEY_FIND, KEYRLS)

KBDFORWARDHLD = IE(LD.EV_KEY.KEY_FORWARD, KEYHLD)
KBDFORWARDPRS = IE(LD.EV_KEY.KEY_FORWARD, KEYPRS)
KBDFORWARDRLS = IE(LD.EV_KEY.KEY_FORWARD, KEYRLS)

KBDFRONTHLD = IE(LD.EV_KEY.KEY_FRONT, KEYHLD)
KBDFRONTPRS = IE(LD.EV_KEY.KEY_FRONT, KEYPRS)
KBDFRONTRLS = IE(LD.EV_KEY.KEY_FRONT, KEYRLS)

KBDGHLD = IE(LD.EV_KEY.KEY_G, KEYHLD)
KBDGPRS = IE(LD.EV_KEY.KEY_G, KEYPRS)
KBDGRLS = IE(LD.EV_KEY.KEY_G, KEYRLS)

KBDGRAVEHLD = IE(LD.EV_KEY.KEY_GRAVE, KEYHLD)
KBDGRAVEPRS = IE(LD.EV_KEY.KEY_GRAVE, KEYPRS)
KBDGRAVERLS = IE(LD.EV_KEY.KEY_GRAVE, KEYRLS)

KBDHANGUELHLD = IE(LD.EV_KEY.KEY_HANGEUL, KEYHLD)
KBDHANGUELPRS = IE(LD.EV_KEY.KEY_HANGEUL, KEYPRS)
KBDHANGUELRLS = IE(LD.EV_KEY.KEY_HANGEUL, KEYRLS)

KBDHANJAHLD = IE(LD.EV_KEY.KEY_HANJA, KEYHLD)
KBDHANJAPRS = IE(LD.EV_KEY.KEY_HANJA, KEYPRS)
KBDHANJARLS = IE(LD.EV_KEY.KEY_HANJA, KEYRLS)

KBDHELPHLD = IE(LD.EV_KEY.KEY_HELP, KEYHLD)
KBDHELPPRS = IE(LD.EV_KEY.KEY_HELP, KEYPRS)
KBDHELPRLS = IE(LD.EV_KEY.KEY_HELP, KEYRLS)

KBDHENKANHLD = IE(LD.EV_KEY.KEY_HENKAN, KEYHLD)
KBDHENKANPRS = IE(LD.EV_KEY.KEY_HENKAN, KEYPRS)
KBDHENKANRLS = IE(LD.EV_KEY.KEY_HENKAN, KEYRLS)

KBDHHLD = IE(LD.EV_KEY.KEY_H, KEYHLD)
KBDHPRS = IE(LD.EV_KEY.KEY_H, KEYPRS)
KBDHRLS = IE(LD.EV_KEY.KEY_H, KEYRLS)

KBDHIRAGANAHLD = IE(LD.EV_KEY.KEY_HIRAGANA, KEYHLD)
KBDHIRAGANAPRS = IE(LD.EV_KEY.KEY_HIRAGANA, KEYPRS)
KBDHIRAGANARLS = IE(LD.EV_KEY.KEY_HIRAGANA, KEYRLS)

KBDHOMEHLD = IE(LD.EV_KEY.KEY_HOME, KEYHLD)
KBDHOMEPRS = IE(LD.EV_KEY.KEY_HOME, KEYPRS)
KBDHOMERLS = IE(LD.EV_KEY.KEY_HOME, KEYRLS)

KBDIHLD = IE(LD.EV_KEY.KEY_I, KEYHLD)
KBDIPRS = IE(LD.EV_KEY.KEY_I, KEYPRS)
KBDIRLS = IE(LD.EV_KEY.KEY_I, KEYRLS)

KBDINSERTHLD = IE(LD.EV_KEY.KEY_INSERT, KEYHLD)
KBDINSERTPRS = IE(LD.EV_KEY.KEY_INSERT, KEYPRS)
KBDINSERTRLS = IE(LD.EV_KEY.KEY_INSERT, KEYRLS)

KBDJHLD = IE(LD.EV_KEY.KEY_J, KEYHLD)
KBDJPRS = IE(LD.EV_KEY.KEY_J, KEYPRS)
KBDJRLS = IE(LD.EV_KEY.KEY_J, KEYRLS)

KBDKATAKANAHLD = IE(LD.EV_KEY.KEY_KATAKANA, KEYHLD)
KBDKATAKANAPRS = IE(LD.EV_KEY.KEY_KATAKANA, KEYPRS)
KBDKATAKANARLS = IE(LD.EV_KEY.KEY_KATAKANA, KEYRLS)

KBDKATAKANAHIRAGANAHLD = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYHLD)
KBDKATAKANAHIRAGANAPRS = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYPRS)
KBDKATAKANAHIRAGANARLS = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYRLS)

KBDKHLD = IE(LD.EV_KEY.KEY_K, KEYHLD)
KBDKPRS = IE(LD.EV_KEY.KEY_K, KEYPRS)
KBDKRLS = IE(LD.EV_KEY.KEY_K, KEYRLS)

KBDKP0HLD = IE(LD.EV_KEY.KEY_KP0, KEYHLD)
KBDKP0PRS = IE(LD.EV_KEY.KEY_KP0, KEYPRS)
KBDKP0RLS = IE(LD.EV_KEY.KEY_KP0, KEYRLS)

KBDKP1HLD = IE(LD.EV_KEY.KEY_KP1, KEYHLD)
KBDKP1PRS = IE(LD.EV_KEY.KEY_KP1, KEYPRS)
KBDKP1RLS = IE(LD.EV_KEY.KEY_KP1, KEYRLS)

KBDKP2HLD = IE(LD.EV_KEY.KEY_KP2, KEYHLD)
KBDKP2PRS = IE(LD.EV_KEY.KEY_KP2, KEYPRS)
KBDKP2RLS = IE(LD.EV_KEY.KEY_KP2, KEYRLS)

KBDKP3HLD = IE(LD.EV_KEY.KEY_KP3, KEYHLD)
KBDKP3PRS = IE(LD.EV_KEY.KEY_KP3, KEYPRS)
KBDKP3RLS = IE(LD.EV_KEY.KEY_KP3, KEYRLS)

KBDKP4HLD = IE(LD.EV_KEY.KEY_KP4, KEYHLD)
KBDKP4PRS = IE(LD.EV_KEY.KEY_KP4, KEYPRS)
KBDKP4RLS = IE(LD.EV_KEY.KEY_KP4, KEYRLS)

KBDKP5HLD = IE(LD.EV_KEY.KEY_KP5, KEYHLD)
KBDKP5PRS = IE(LD.EV_KEY.KEY_KP5, KEYPRS)
KBDKP5RLS = IE(LD.EV_KEY.KEY_KP5, KEYRLS)

KBDKP6HLD = IE(LD.EV_KEY.KEY_KP6, KEYHLD)
KBDKP6PRS = IE(LD.EV_KEY.KEY_KP6, KEYPRS)
KBDKP6RLS = IE(LD.EV_KEY.KEY_KP6, KEYRLS)

KBDKP7HLD = IE(LD.EV_KEY.KEY_KP7, KEYHLD)
KBDKP7PRS = IE(LD.EV_KEY.KEY_KP7, KEYPRS)
KBDKP7RLS = IE(LD.EV_KEY.KEY_KP7, KEYRLS)

KBDKP8HLD = IE(LD.EV_KEY.KEY_KP8, KEYHLD)
KBDKP8PRS = IE(LD.EV_KEY.KEY_KP8, KEYPRS)
KBDKP8RLS = IE(LD.EV_KEY.KEY_KP8, KEYRLS)

KBDKP9HLD = IE(LD.EV_KEY.KEY_KP9, KEYHLD)
KBDKP9PRS = IE(LD.EV_KEY.KEY_KP9, KEYPRS)
KBDKP9RLS = IE(LD.EV_KEY.KEY_KP9, KEYRLS)

KBDKPCOMMAHLD = IE(LD.EV_KEY.KEY_KPCOMMA, KEYHLD)
KBDKPCOMMAPRS = IE(LD.EV_KEY.KEY_KPCOMMA, KEYPRS)
KBDKPCOMMARLS = IE(LD.EV_KEY.KEY_KPCOMMA, KEYRLS)

KBDKPDOTHLD = IE(LD.EV_KEY.KEY_KPDOT, KEYHLD)
KBDKPDOTPRS = IE(LD.EV_KEY.KEY_KPDOT, KEYPRS)
KBDKPDOTRLS = IE(LD.EV_KEY.KEY_KPDOT, KEYRLS)

KBDKPENTERHLD = IE(LD.EV_KEY.KEY_KPENTER, KEYHLD)
KBDKPENTERPRS = IE(LD.EV_KEY.KEY_KPENTER, KEYPRS)
KBDKPENTERRLS = IE(LD.EV_KEY.KEY_KPENTER, KEYRLS)

KBDKPJPCOMMAHLD = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYHLD)
KBDKPJPCOMMAPRS = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYPRS)
KBDKPJPCOMMARLS = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYRLS)

KBDKPLPARENHLD = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYHLD)
KBDKPLPARENPRS = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYPRS)
KBDKPLPARENRLS = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYRLS)

KBDKPMINUSHLD = IE(LD.EV_KEY.KEY_KPMINUS, KEYHLD)
KBDKPMINUSPRS = IE(LD.EV_KEY.KEY_KPMINUS, KEYPRS)
KBDKPMINUSRLS = IE(LD.EV_KEY.KEY_KPMINUS, KEYRLS)

KBDKPPLUSHLD = IE(LD.EV_KEY.KEY_KPPLUS, KEYHLD)
KBDKPPLUSPRS = IE(LD.EV_KEY.KEY_KPPLUS, KEYPRS)
KBDKPPLUSRLS = IE(LD.EV_KEY.KEY_KPPLUS, KEYRLS)

KBDKPRPARENHLD = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYHLD)
KBDKPRPARENPRS = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYPRS)
KBDKPRPARENRLS = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYRLS)

KBDKPSLASHHLD = IE(LD.EV_KEY.KEY_KPSLASH, KEYHLD)
KBDKPSLASHPRS = IE(LD.EV_KEY.KEY_KPSLASH, KEYPRS)
KBDKPSLASHRLS = IE(LD.EV_KEY.KEY_KPSLASH, KEYRLS)

KBDKPSPLATHLD = IE(LD.EV_KEY.KEY_KPASTERISK, KEYHLD)
KBDKPSPLATPRS = IE(LD.EV_KEY.KEY_KPASTERISK, KEYPRS)
KBDKPSPLATRLS = IE(LD.EV_KEY.KEY_KPASTERISK, KEYRLS)

KBDLBRACEHLD = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYHLD)
KBDLBRACEPRS = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYPRS)
KBDLBRACERLS = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYRLS)

KBDLCTRLHLD = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYHLD)
KBDLCTRLPRS = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYPRS)
KBDLCTRLRLS = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYRLS)

KBDLTHLD = IE(LD.EV_KEY.KEY_LEFT, KEYHLD)
KBDLTPRS = IE(LD.EV_KEY.KEY_LEFT, KEYPRS)
KBDLTRLS = IE(LD.EV_KEY.KEY_LEFT, KEYRLS)

KBDLHLD = IE(LD.EV_KEY.KEY_L, KEYHLD)
KBDLPRS = IE(LD.EV_KEY.KEY_L, KEYPRS)
KBDLRLS = IE(LD.EV_KEY.KEY_L, KEYRLS)

KBDLMETAHLD = IE(LD.EV_KEY.KEY_LEFTMETA, KEYHLD)
KBDLMETAPRS = IE(LD.EV_KEY.KEY_LEFTMETA, KEYPRS)
KBDLMETARLS = IE(LD.EV_KEY.KEY_LEFTMETA, KEYRLS)

KBDLSHIFTHLD = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYHLD)
KBDLSHIFTPRS = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYPRS)
KBDLSHIFTRLS = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYRLS)

KBDMHLD = IE(LD.EV_KEY.KEY_M, KEYHLD)
KBDMPRS = IE(LD.EV_KEY.KEY_M, KEYPRS)
KBDMRLS = IE(LD.EV_KEY.KEY_M, KEYRLS)

KBDMINUSHLD = IE(LD.EV_KEY.KEY_MINUS, KEYHLD)
KBDMINUSPRS = IE(LD.EV_KEY.KEY_MINUS, KEYPRS)
KBDMINUSRLS = IE(LD.EV_KEY.KEY_MINUS, KEYRLS)

KBDMUHENKANHLD = IE(LD.EV_KEY.KEY_MUHENKAN, KEYHLD)
KBDMUHENKANPRS = IE(LD.EV_KEY.KEY_MUHENKAN, KEYPRS)
KBDMUHENKANRLS = IE(LD.EV_KEY.KEY_MUHENKAN, KEYRLS)

KBDMUTEHLD = IE(LD.EV_KEY.KEY_MUTE, KEYHLD)
KBDMUTEPRS = IE(LD.EV_KEY.KEY_MUTE, KEYPRS)
KBDMUTERLS = IE(LD.EV_KEY.KEY_MUTE, KEYRLS)

KBDNHLD = IE(LD.EV_KEY.KEY_N, KEYHLD)
KBDNPRS = IE(LD.EV_KEY.KEY_N, KEYPRS)
KBDNRLS = IE(LD.EV_KEY.KEY_N, KEYRLS)

KBDNEXTSONGHLD = IE(LD.EV_KEY.KEY_NEXTSONG, KEYHLD)
KBDNEXTSONGPRS = IE(LD.EV_KEY.KEY_NEXTSONG, KEYPRS)
KBDNEXTSONGRLS = IE(LD.EV_KEY.KEY_NEXTSONG, KEYRLS)

KBDNUMLKHLD = IE(LD.EV_KEY.KEY_NUMLOCK, KEYHLD)
KBDNUMLKPRS = IE(LD.EV_KEY.KEY_NUMLOCK, KEYPRS)
KBDNUMLKRLS = IE(LD.EV_KEY.KEY_NUMLOCK, KEYRLS)

KBDOHLD = IE(LD.EV_KEY.KEY_O, KEYHLD)
KBDOPRS = IE(LD.EV_KEY.KEY_O, KEYPRS)
KBDORLS = IE(LD.EV_KEY.KEY_O, KEYRLS)

KBDOPENHLD = IE(LD.EV_KEY.KEY_OPEN, KEYHLD)
KBDOPENPRS = IE(LD.EV_KEY.KEY_OPEN, KEYPRS)
KBDOPENRLS = IE(LD.EV_KEY.KEY_OPEN, KEYRLS)

KBDPASTEHLD = IE(LD.EV_KEY.KEY_PASTE, KEYHLD)
KBDPASTEPRS = IE(LD.EV_KEY.KEY_PASTE, KEYPRS)
KBDPASTERLS = IE(LD.EV_KEY.KEY_PASTE, KEYRLS)

KBDPAUSEHLD = IE(LD.EV_KEY.KEY_PAUSE, KEYHLD)
KBDPAUSEPRS = IE(LD.EV_KEY.KEY_PAUSE, KEYPRS)
KBDPAUSERLS = IE(LD.EV_KEY.KEY_PAUSE, KEYRLS)

KBDPGDNHLD = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYHLD)
KBDPGDNPRS = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYPRS)
KBDPGDNRLS = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYRLS)

KBDPGUPHLD = IE(LD.EV_KEY.KEY_PAGEUP, KEYHLD)
KBDPGUPPRS = IE(LD.EV_KEY.KEY_PAGEUP, KEYPRS)
KBDPGUPRLS = IE(LD.EV_KEY.KEY_PAGEUP, KEYRLS)

KBDPHLD = IE(LD.EV_KEY.KEY_P, KEYHLD)
KBDPPRS = IE(LD.EV_KEY.KEY_P, KEYPRS)
KBDPRLS = IE(LD.EV_KEY.KEY_P, KEYRLS)

KBDPLAYPAUSEHLD = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYHLD)
KBDPLAYPAUSEPRS = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYPRS)
KBDPLAYPAUSERLS = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYRLS)

KBDPOWERHLD = IE(LD.EV_KEY.KEY_POWER, KEYHLD)
KBDPOWERPRS = IE(LD.EV_KEY.KEY_POWER, KEYPRS)
KBDPOWERRLS = IE(LD.EV_KEY.KEY_POWER, KEYRLS)

KBDPREVIOUSSONGHLD = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYHLD)
KBDPREVIOUSSONGPRS = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYPRS)
KBDPREVIOUSSONGRLS = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYRLS)

KBDPROPSHLD = IE(LD.EV_KEY.KEY_PROPS, KEYHLD)
KBDPROPSPRS = IE(LD.EV_KEY.KEY_PROPS, KEYPRS)
KBDPROPSRLS = IE(LD.EV_KEY.KEY_PROPS, KEYRLS)

KBDQHLD = IE(LD.EV_KEY.KEY_Q, KEYHLD)
KBDQPRS = IE(LD.EV_KEY.KEY_Q, KEYPRS)
KBDQRLS = IE(LD.EV_KEY.KEY_Q, KEYRLS)

KBDRHLD = IE(LD.EV_KEY.KEY_R, KEYHLD)
KBDRPRS = IE(LD.EV_KEY.KEY_R, KEYPRS)
KBDRRLS = IE(LD.EV_KEY.KEY_R, KEYRLS)

KBDR0HLD = IE(LD.EV_KEY.KEY_RO, KEYHLD)
KBDR0PRS = IE(LD.EV_KEY.KEY_RO, KEYPRS)
KBDR0RLS = IE(LD.EV_KEY.KEY_RO, KEYRLS)

KBDRALTHLD = IE(LD.EV_KEY.KEY_RIGHTALT, KEYHLD)
KBDRALTPRS = IE(LD.EV_KEY.KEY_RIGHTALT, KEYPRS)
KBDRALTRLS = IE(LD.EV_KEY.KEY_RIGHTALT, KEYRLS)

KBDRBRACEHLD = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYHLD)
KBDRBRACEPRS = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYPRS)
KBDRBRACERLS = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYRLS)

KBDRCTRLHLD = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYHLD)
KBDRCTRLPRS = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYPRS)
KBDRCTRLRLS = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYRLS)

KBDRTHLD = IE(LD.EV_KEY.KEY_RIGHT, KEYHLD)
KBDRTPRS = IE(LD.EV_KEY.KEY_RIGHT, KEYPRS)
KBDRTRLS = IE(LD.EV_KEY.KEY_RIGHT, KEYRLS)

KBDRMETAHLD = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYHLD)
KBDRMETAPRS = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYPRS)
KBDRMETARLS = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYRLS)

KBDRSHIFTHLD = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYHLD)
KBDRSHIFTPRS = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYPRS)
KBDRSHIFTRLS = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYRLS)

KBDSCROLLDNHLD = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYHLD)
KBDSCROLLDNPRS = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYPRS)
KBDSCROLLDNRLS = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYRLS)

KBDSCROLLLKHLD = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYHLD)
KBDSCROLLLKPRS = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYPRS)
KBDSCROLLLKRLS = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYRLS)

KBDSCROLLUPHLD = IE(LD.EV_KEY.KEY_SCROLLUP, KEYHLD)
KBDSCROLLUPPRS = IE(LD.EV_KEY.KEY_SCROLLUP, KEYPRS)
KBDSCROLLUPRLS = IE(LD.EV_KEY.KEY_SCROLLUP, KEYRLS)

KBDSEMICOLONHLD = IE(LD.EV_KEY.KEY_SEMICOLON, KEYHLD)
KBDSEMICOLONPRS = IE(LD.EV_KEY.KEY_SEMICOLON, KEYPRS)
KBDSEMICOLONRLS = IE(LD.EV_KEY.KEY_SEMICOLON, KEYRLS)

KBDSHLD = IE(LD.EV_KEY.KEY_S, KEYHLD)
KBDSPRS = IE(LD.EV_KEY.KEY_S, KEYPRS)
KBDSRLS = IE(LD.EV_KEY.KEY_S, KEYRLS)

KBDSLASHHLD = IE(LD.EV_KEY.KEY_SLASH, KEYHLD)
KBDSLASHPRS = IE(LD.EV_KEY.KEY_SLASH, KEYPRS)
KBDSLASHRLS = IE(LD.EV_KEY.KEY_SLASH, KEYRLS)

KBDSLEEPHLD = IE(LD.EV_KEY.KEY_SLEEP, KEYHLD)
KBDSLEEPPRS = IE(LD.EV_KEY.KEY_SLEEP, KEYPRS)
KBDSLEEPRLS = IE(LD.EV_KEY.KEY_SLEEP, KEYRLS)

KBDSPCHLD = IE(LD.EV_KEY.KEY_SPACE, KEYHLD)
KBDSPCPRS = IE(LD.EV_KEY.KEY_SPACE, KEYPRS)
KBDSPCRLS = IE(LD.EV_KEY.KEY_SPACE, KEYRLS)

KBDSTOPCDHLD = IE(LD.EV_KEY.KEY_STOPCD, KEYHLD)
KBDSTOPCDPRS = IE(LD.EV_KEY.KEY_STOPCD, KEYPRS)
KBDSTOPCDRLS = IE(LD.EV_KEY.KEY_STOPCD, KEYRLS)

KBDSTOPHLD = IE(LD.EV_KEY.KEY_STOP, KEYHLD)
KBDSTOPPRS = IE(LD.EV_KEY.KEY_STOP, KEYPRS)
KBDSTOPRLS = IE(LD.EV_KEY.KEY_STOP, KEYRLS)

KBDSYSRQHLD = IE(LD.EV_KEY.KEY_SYSRQ, KEYHLD)
KBDSYSRQPRS = IE(LD.EV_KEY.KEY_SYSRQ, KEYPRS)
KBDSYSRQRLS = IE(LD.EV_KEY.KEY_SYSRQ, KEYRLS)

KBDTABHLD = IE(LD.EV_KEY.KEY_TAB, KEYHLD)
KBDTABPRS = IE(LD.EV_KEY.KEY_TAB, KEYPRS)
KBDTABRLS = IE(LD.EV_KEY.KEY_TAB, KEYRLS)

KBDTHLD = IE(LD.EV_KEY.KEY_T, KEYHLD)
KBDTPRS = IE(LD.EV_KEY.KEY_T, KEYPRS)
KBDTRLS = IE(LD.EV_KEY.KEY_T, KEYRLS)

KBDUHLD = IE(LD.EV_KEY.KEY_U, KEYHLD)
KBDUPRS = IE(LD.EV_KEY.KEY_U, KEYPRS)
KBDURLS = IE(LD.EV_KEY.KEY_U, KEYRLS)

KBDUNDOHLD = IE(LD.EV_KEY.KEY_UNDO, KEYHLD)
KBDUNDOPRS = IE(LD.EV_KEY.KEY_UNDO, KEYPRS)
KBDUNDORLS = IE(LD.EV_KEY.KEY_UNDO, KEYRLS)

KBDUNKNOWNHLD = IE(LD.EV_KEY.KEY_UNKNOWN, KEYHLD)
KBDUNKNOWNPRS = IE(LD.EV_KEY.KEY_UNKNOWN, KEYPRS)
KBDUNKNOWNRLS = IE(LD.EV_KEY.KEY_UNKNOWN, KEYRLS)

KBDUPHLD = IE(LD.EV_KEY.KEY_UP, KEYHLD)
KBDUPPRS = IE(LD.EV_KEY.KEY_UP, KEYPRS)
KBDUPRLS = IE(LD.EV_KEY.KEY_UP, KEYRLS)

KBDVHLD = IE(LD.EV_KEY.KEY_V, KEYHLD)
KBDVPRS = IE(LD.EV_KEY.KEY_V, KEYPRS)
KBDVRLS = IE(LD.EV_KEY.KEY_V, KEYRLS)

KBDVOLDNHLD = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYHLD)
KBDVOLDNPRS = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYPRS)
KBDVOLDNRLS = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYRLS)

KBDVOLUPHLD = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYHLD)
KBDVOLUPPRS = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYPRS)
KBDVOLUPRLS = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYRLS)

KBDWHLD = IE(LD.EV_KEY.KEY_W, KEYHLD)
KBDWPRS = IE(LD.EV_KEY.KEY_W, KEYPRS)
KBDWRLS = IE(LD.EV_KEY.KEY_W, KEYRLS)

KBDWWWHLD = IE(LD.EV_KEY.KEY_WWW, KEYHLD)
KBDWWWPRS = IE(LD.EV_KEY.KEY_WWW, KEYPRS)
KBDWWWRLS = IE(LD.EV_KEY.KEY_WWW, KEYRLS)

KBDXHLD = IE(LD.EV_KEY.KEY_X, KEYHLD)
KBDXPRS = IE(LD.EV_KEY.KEY_X, KEYPRS)
KBDXRLS = IE(LD.EV_KEY.KEY_X, KEYRLS)

KBDYENHLD = IE(LD.EV_KEY.KEY_YEN, KEYHLD)
KBDYENPRS = IE(LD.EV_KEY.KEY_YEN, KEYPRS)
KBDYENRLS = IE(LD.EV_KEY.KEY_YEN, KEYRLS)

KBDYHLD = IE(LD.EV_KEY.KEY_Y, KEYHLD)
KBDYPRS = IE(LD.EV_KEY.KEY_Y, KEYPRS)
KBDYRLS = IE(LD.EV_KEY.KEY_Y, KEYRLS)

KBDREFRESHHLD = IE(LD.EV_KEY.KEY_REFRESH, KEYHLD)
KBDREFRESHPRS = IE(LD.EV_KEY.KEY_REFRESH, KEYPRS)
KBDREFRESHRLS = IE(LD.EV_KEY.KEY_REFRESH, KEYRLS)

KBDZENKAKUHANKAKUHLD = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYHLD)
KBDZENKAKUHANKAKUPRS = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYPRS)
KBDZENKAKUHANKAKURLS = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYRLS)

KBDZHLD = IE(LD.EV_KEY.KEY_Z, KEYHLD)
KBDZPRS = IE(LD.EV_KEY.KEY_Z, KEYPRS)
KBDZRLS = IE(LD.EV_KEY.KEY_Z, KEYRLS)

# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * end of constants.py cut 20200819.003108
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
