

import libevdev as LD
from libevdev import InputEvent as IE


from dataStuff import constants as C


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# (1) string and character and value section
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#


AX_ALTD = "AX_ALTD"
AX_CTRLQ = "AX_CTRLQ"
AX_CTRLS = "AX_CTRLS"
AX_F = "AX_F"
AX_F5 = "AX_F5"
AX_F6 = "AX_F6"
AX_INSERT = "AX_INSERT"
AX_N = "AX_N"
AX_Q = "AX_Q"
AX_SHIFTTAB = "AX_SHIFTTAB"
AX_TAB = "AX_TAB"
AX_Y = "AX_Y"
AXALTC = "AXALTC"
AXALTTAB = "AXALTTAB"
AXCRSRDN = "AXCRSRDN"
AXCRSRLT = "AXCRSRLT"
AXCRSRRT = "AXCRSRRT"
AXCRSRUP = "AXCRSRUP"
AXCTRLTAB = "AXCTRLTAB"
AXDEL = "AXDEL"
AXDSKTP1 = "AXDSKTP1"
AXDSKTP2 = "AXDSKTP2"
AXDSKTP3 = "AXDSKTP3"
AXDSKTP4 = "AXDSKTP4"
AXESC = "AXESC"
AXGIMPOVWRT = "AXGIMPOVWRT"
AXHRHWLDN = "AXHRHWLDN"
AXHRHWLLT = "AXHRHWLLT"
AXHRHWLRT = "AXHRHWLRT"
AXHRHWLUP = "AXHRHWLUP"
AXMCCOPY = "AXMCCOPY"
AXMCDEL = "AXMCDEL"
AXMCMOVE = "AXMCMOVE"
AXMCSEL = "AXMCSEL"
AXMSEBTNBAK = "AXMSEBTNBAK"
AXMSEBTNFWD = "AXMSEBTNFWD"
AXMSEBTNLT = "AXMSEBTNLT"
AXMSEBTNMID = "AXMSEBTNMID"
AXMSEBTNRT = "AXMSEBTNRT"
AXMSEBTNSIDE = "AXMSEBTNSIDE"
AXMSEBTNTASK = "AXMSEBTNTASK"
AXMSEDN = "AXMSEDN"
AXMSELT = "AXMSELT"
AXMSERT = "AXMSERT"
AXMSEUP = "AXMSEUP"
AXPROFAXDEF = "AXPROFAXDEF"
AXPROFDICTKEY = "AXPROFDICTKEY"
AXSAVE = "AXSAVE"
AXSHIFTX = "AXSHIFTX"
AXWHLDN = "AXWHLDN"
AXWHLLT = "AXWHLLT"
AXWHLRT = "AXWHLRT"
AXWHLUP = "AXWHLUP"
AXXNVCOPY = "AXXNVCOPY"
AXXNVCROP = "AXXNVCROP"
AXXNVFLIPH = "AXXNVFLIPH"
AXXNVMOVE = "AXXNVMOVE"
AXXNVROTLT = "AXXNVROTLT"
AXXNVROTRT = "AXXNVROTRT"
AXXNVSEL2TOP = "AXXNVSEL2TOP"


ACTIONS = {
	AXALTTAB: [
		C.KBDALTLPRS,
		C.KBDTABPRS,
		C.KBDTABRLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXXNVCOPY: [
		C.KBDALTLPRS,
		C.KBDCPRS,
		C.KBDCRLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXALTC: [
		C.KBDALTLPRS,
		C.KBDCPRS,
		C.KBDCRLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXXNVCROP: [
		C.KBDLSHIFTPRS,
		C.KBDXPRS,
		C.KBDXRLS,
		C.KBDLSHIFTRLS,
		C.SYNREPORT,
	],
	AXSHIFTX: [
		C.KBDLSHIFTPRS,
		C.KBDXPRS,
		C.KBDXRLS,
		C.KBDLSHIFTRLS,
		C.SYNREPORT,
	],
	AXCRSRDN: [
		C.KBDDNPRS,
		C.KBDDNRLS,
		C.SYNREPORT,
	],
	AXCRSRLT: [
		C.KBDLTPRS,
		C.KBDLTRLS,
		C.SYNREPORT,
	],
	AXCRSRRT: [
		C.KBDRTPRS,
		C.KBDRTRLS,
		C.SYNREPORT,
	],
	AXCRSRUP: [
		C.KBDUPPRS,
		C.KBDUPRLS,
		C.SYNREPORT,
	],
	AXCTRLTAB: [
		C.KBDLCTRLPRS,
		C.KBDTABPRS,
		C.KBDTABRLS,
		C.KBDLCTRLRLS,
		C.SYNREPORT,
	],
	AXDEL: [
		C.KBDDELPRS,
		C.KBDDELRLS,
		C.SYNREPORT,
	],
	AXDSKTP1: [
		C.KBDALTLPRS,
		C.KBD1PRS,
		C.KBD1RLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXDSKTP2: [
		C.KBDALTLPRS,
		C.KBD2PRS,
		C.KBD2RLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXDSKTP3: [
		C.KBDALTLPRS,
		C.KBD3PRS,
		C.KBD3RLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXDSKTP4: [
		C.KBDALTLPRS,
		C.KBD4PRS,
		C.KBD4RLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXESC: [
		C.KBDESCPRS,
		C.KBDESCRLS,
		C.SYNREPORT,
	],
	AXMCMOVE: [
		C.KBDF6PRS,
		C.KBDF6RLS,
		C.KBDENTERPRS,
		C.KBDENTERRLS,
		C.SYNREPORT,
	],
	AXMCCOPY: [
		C.KBDF5PRS,
		C.KBDF5RLS,
		C.KBDENTERPRS,
		C.KBDENTERRLS,
		C.SYNREPORT,
	],
	AXMCDEL: [
		C.KBDF8PRS,
		C.KBDF8RLS,
		C.SYNREPORT,
	],
	AXXNVFLIPH: [
		C.KBDALTLPRS,
		C.KBDFPRS,
		C.KBDFRLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXXNVMOVE: [
		C.KBDALTLPRS,
		C.KBDMPRS,
		C.KBDMRLS,
		C.KBDALTLRLS,
		C.SYNREPORT,
	],
	AXMSEBTNBAK: [
		C.MSEBAKBTNPRSHLD,
		C.SYNREPORT,
		C.MSEBAKBTNRLS,
		C.SYNREPORT,
	]
	AXMSEBTNFWD: [
		C.MSEFWDBTNPRSHLD,
		C.SYNREPORT,
		C.MSEFWDBTNRLS,
		C.SYNREPORT,
	],
	AXMSEBTNLT: [
		C.MSELTBTNPRSHLD,
		C.SYNREPORT,
		C.MSELTBTNRLS,
		C.SYNREPORT,
	],
	AXMSEBTNMID: [
		C.MSEMIDBTNPRSHLD,
		C.SYNREPORT,
		C.MSEMIDBTNRLS,
		C.SYNREPORT,
	],
	AXMSEBTNRT: [
		C.MSERTBTNPRSHLD,
		C.SYNREPORT,
		C.MSERTBTNRLS,
		C.SYNREPORT,
	],
	AXMSEBTNSIDE: [
		C.MSESIDEBTNPRSHLD,
		C.SYNREPORT,
		C.MSESIDEBTNRLS,
		C.SYNREPORT,
	],
	AXMSEBTNTASK: [
		C.MSETASKBTNPRSHLD,
		C.SYNREPORT,
		C.MSETASKBTNRLS,
		C.SYNREPORT,
	],
	AXMSEDN: [
		C.MSEDN,
		C.SYNREPORT,
	],
	AXMSELT: [
		C.MSELT,
		C.SYNREPORT,
	],
	AXMSERT: [
		C.MSERT,
		C.SYNREPORT,
	],
	AXMSEUP: [
		C.MSERT,
		C.SYNREPORT,
	],
	AXXNVROTLT: [
		C.KBDLCTRLPRS,
		C.KBDLSHIFTPRS,
		C.KBDLPRS,
		C.KBDLRLS,
		C.KBDLSHIFTRLS,
		C.KBDLCTRLRLS,
		C.SYNREPORT,
	],
	AXXNVROTRT: [
		C.KBDLCTRLPRS,
		C.KBDLSHIFTPRS,
		C.KBDRPRS,
		C.KBDRRLS,
		C.KBDLSHIFTRLS,
		C.KBDLCTRLRLS,
		C.SYNREPORT,
	],
	AXSAVE: [
		C.KBDLCTRLPRS,
		C.KBDSPRS,
		C.KBDSRLS,
		C.KBDLCTRLRLS,
		C.SYNREPORT,
	],
	AX_CTRLS: [
		C.KBDLCTRLPRS,
		C.KBDSPRS,
		C.KBDSRLS,
		C.KBDLCTRLRLS,
		C.SYNREPORT,
	],
	AX_SHIFTTAB: [
		C.KBDLSHIFTPRS,
		C.KBDTABPRS,
		C.KBDTABRLS,
		C.KBDLSHIFTRLS,
		C.SYNREPORT,
	],
	AX_TAB: [
		C.KBDTABPRS,
		C.KBDTABRLS,
		C.SYNREPORT,
	],
	AXWHLDN: [
		C.MSEWHLDN,
		C.SYNREPORT,
	],
	AXWHLLT: [
		C.MSEWHLLT,
		C.SYNREPORT,
	],
	AXWHLRT: [
		C.MSEWHLRT,
		C.SYNREPORT,
	],
	AXWHLUP: [
		C.MSEWHLUP,
		C.SYNREPORT,
	],
	AXHRWHLDN: [
		C.MSEHRWHLDN,
		C.SYNREPORT,
	],
	AXHRWHLLT: [
		C.MSEHRWHLLT,
		C.SYNREPORT,
	],
	AXHRWHLRT: [
		C.MSEHRWHLRT,
		C.SYNREPORT,
	],
	AXHRWHLUP: [
		C.MSEHRWHLUP,
		C.SYNREPORT,
	],
	AXMCSEL: [
		C.KBDINSERTPRS,
		C.KBDINSERTRLS,
		C.SYNREPORT,
	],
	AX_INSERT: [
		C.KBDINSERTPRS,
		C.KBDINSERTRLS,
		C.SYNREPORT,
	],
	AX_ALTD: [
		C.KBDALTLPRS,
		C.KBDDPRS,
		C.KBDDRLS,
		C.KBDALTLRLS,
	],
}


devices = {

}
