import libevdev as LD
from libevdev import InputEvent as IE


# constants start here
DEBUGME = False
JOYSTICKNAME01 = 'ShanWan     GAME:PAD S PRO-BLUETOOTH-V6.20'
GPMNAME = 'Griffin PowerMate'
FFFF = 0xffff
TICKSDEFAULT = 1500  # how many SS between repeats
TICKSCURSOR = 1800  # how many ticks between cursor events
TICKSMOUSE = 500  # how many ticks between mouse movement activations
DELAYTICKS = 2  # how many ticks to wait until repeating starts
# life gets really weird if this is not included, only on the chance that you
# happen to hit a perfectly timed loop, about 1-20 repeat uses, this makes those
# only a little annoying, short delay before repeats when that perfect timing happens
ERRTRYDEFAULT = 10000  # HOW MANY TICKS BETWEEN RETRY ATTEMPTS ON MISSING DEVICES
# event.value button/key constants
KEYPRSHLD = 3  # output event seems to be how you make a mouse button work as expected along with a syn after the
# press and release both
KEYHLD = 2  # output key held event
KEYPRS = 1  # output key pressed event
KEYRLS = 0  # output key rel;eased event

# ABS distances per triggered event
MOUSEDISTANCE = 5  # how far to move the mouse per event
WHEELDISTANCE = 1  # how many clicks of the wheel per event

# ABS status constants
ABSEVENTMIN = -65500
ABSEVENT0 = 65530
ABSEVENTMAX = 65500

# joystick event constant
JOYSTICKMID = 128
JOYSTICKDEAD = 100
JOYSTICKMAX = 255
JOYSTICKMIN = 0

# hat constants
HATMAX = 1
HATMID = 0
HATMIN = -1

# rel constants
RELUP = 1
RELZERO = 0
RELDOWN = -1

# constants used in the profile dictionaries
# these are unique only among values used to indicate the 1st level of a profile event entry
ZERODUDE = 0  # used for comic relief
EVENTNAME = ZERODUDE + 1  # hashtbl rqd on all profiles
EVENTDESCRIPTION = EVENTNAME + 1  # str rqd on all event types
EVENTINBTNS = EVENTDESCRIPTION + 1  # lst rqd on all events involving keys input
EVENTOUTNORM = EVENTINBTNS + 1  # lst rqd on all events from btn only input
PROFILEENTRYTYPE = EVENTOUTNORM + 1  # str rqd on all profile default entries
PROFILENAME = PROFILEENTRYTYPE + 1  # str rqd on all profile defaults entries
PROFILEDESCRIPTION = PROFILENAME + 1  # str required on all profile default entries
EVENTOUTABS = PROFILEDESCRIPTION + 1  # hashtbl rqd on all events involving ABS input, all direction entries are rqd on each
RELOUTEVENTS = EVENTOUTABS + 1  # lst rqd on all events involving REL input
EVENTDATAFLGS = RELOUTEVENTS + 1  # flags rqd on all entries
SPECIALEVENTS = EVENTDATAFLGS + 1  # hashtbl rqd on all special events, special events dict, no checking provided
ADDITIONALDATA = SPECIALEVENTS + 1  # hashtbl rqd on all events with additional data needs, no checking provided
FILENAME = ADDITIONALDATA + 1  # str rqd on all FILEDEFAULTTYPE entries, filename of this profile file
FILEDESCRIPTION = FILENAME + 1  # str rqd on all FILEDEFAULTTYPE entries,file description for this file
PROFILEDEFAULTTYPE = FILEDESCRIPTION + 1  # hashtbl rqd on all profiles
NORMALEVENTTYPE = PROFILEDEFAULTTYPE + 1  # normal kbd mse abs rel events type
SPECIALEVENTTYPE = NORMALEVENTTYPE + 1  # special events type
FILEDEFAULTTYPE = SPECIALEVENTTYPE + 1  # file default type
MAXUSRPRFIL = PROFILEDEFAULTTYPE + 1  # int last currently included profile number
MINUSRPRFIL = MAXUSRPRFIL + 1  # int first user profile number, will be default 0x1000 if not otherwise set
PROFILEPLACEHOLDEREVENTTYPE = MINUSRPRFIL + 1  # future expansion placeholder, must have EVENTDATAFLGS, and PROFILEENTRYTYPE

ENTRYNAMES = \
	{
		EVENTNAME: "EVENTNAME",
		EVENTDESCRIPTION: "EVENTDESCRIPTION",
		EVENTINBTNS: "EVENTINBTNS",
		EVENTOUTNORM: "EVENTOUTNORM",
		PROFILEENTRYTYPE: "PROFILEENTRYTYPE",
		PROFILENAME: "PROFILENAME",
		PROFILEDESCRIPTION: "PROFILEDESCRIPTION",
		EVENTOUTABS: "EVENTOUTABS",
		RELOUTEVENTS: "RELOUTEVENTS",
		EVENTDATAFLGS: "EVENTDATAFLGS",
		SPECIALEVENTS: "SPECIALEVENTS",
		ADDITIONALDATA: "ADDITIONALDATA",
		FILENAME: "FILENAME",
		FILEDESCRIPTION: "FILEDESCRIPTION",
		PROFILEDEFAULTTYPE: "PROFILEDEFAULTTYPE",
		NORMALEVENTTYPE: "NORMALEVENTTYPE",
		SPECIALEVENTTYPE: "SPECIALEVENTTYPE",
		FILEDEFAULTTYPE: "FILEDEFAULTTYPE",
		PROFILEPLACEHOLDEREVENTTYPE: "PROFILEPLACEHOLDEREVENTTYPE",
	}

ENTRYDESCRIPTIONS = \
	{
		EVENTNAME: "str rqd for all event types",
		EVENTDESCRIPTION: "str rqd on all event types",
		EVENTINBTNS: "lst rqd on all events involving keys input",
		EVENTOUTNORM: "lst rqd on all events from btn only input",
		PROFILEENTRYTYPE: "int rqd on all entries profile entry type key",
		PROFILENAME: "str rqd on all profile defaults entries",
		PROFILEDESCRIPTION: "str rqd on all profile default entries",
		EVENTOUTABS: "hashtbl rqd on all events involving ABS input, all direction entries are rqd on each",
		RELOUTEVENTS: "lst rqd on all events involving REL input",
		EVENTDATAFLGS: "flags rqd on all entries",
		SPECIALEVENTS: "hashtbl rqd on all special events, special events dict, no checking provided",
		ADDITIONALDATA: "hashtbl rqd on all events with additional data needs, no checking provided",
		FILENAME: "str rqd on all FILEDEFAULTTYPE entries, filename of this profile file",
		FILEDESCRIPTION: "str rqd on all FILEDEFAULTTYPE entries,file description for this file",
		PROFILEDEFAULTTYPE: "profile default type rqd on all profiles",
		NORMALEVENTTYPE: "normal kbd mse abs rel events type",
		SPECIALEVENTTYPE: "special events type",
		FILEDEFAULTTYPE: "file default type",
		MAXUSRPRFIL: "int last currently included profile number",
		MINUSRPRFIL: "int first user profile number, will be default if not otherwise set",
		PROFILEPLACEHOLDEREVENTTYPE: "future expansion placeholder, must have EVENTDATAFLGS, and PROFILEENTRYTYPE",
	}
RESERVEDTYPESLIST = [PROFILEDEFAULTTYPE, FILEDEFAULTTYPE, PROFILEPLACEHOLDEREVENTTYPE]
ACTIVETYPESLIST = [NORMALEVENTTYPE, SPECIALEVENTTYPE]

# data types flags
DATANONE = 0X0000
DATAINBTN = 0x0001
LDATAINBTNAND = lambda x: x & DATAINBTN
LDATAINBTNOR = lambda x: x | DATAINBTN
DATAOUTABS = 0x0002
LDATAOUTABSAND = lambda x: x & DATAOUTABS
LDATAOUTABSOR = lambda x: x | DATAOUTABS
DATAINREL = 0x0004
LDATAINRELAND = lambda x: x & DATAINREL
LDATAINRELOR = lambda x: x | DATAINREL
DATATICKS = 0x0008
LDATATICKSAND = lambda x: x & DATATICKS
LDATATICKSOR = lambda x: x | DATATICKS
DATAREPEAT = 0x0010
LDATAREPEATAND = lambda x: x & DATAREPEAT
LDATAREPEATOR = lambda x: x | DATAREPEAT
DATAOUTNORM = 0X0020
LDATAOUTNORMAND = lambda x: x & DATAOUTNORM
LDATAOUTNORMOR = lambda x: x | DATAOUTNORM
DATAOUTSPECIAL = 0X0040
LDATASPECIALAND = lambda x: x & DATAOUTSPECIAL
LDATASPECIALOR = lambda x: x | DATAOUTSPECIAL
DATAADD = 0x0080
LDATAADDAND = lambda x: x & DATAADD
LDATAADDOR = lambda x: x | DATAADD
DATAINLTSTK = 0x0100
LDATAINLTSTKAND = lambda x: x & DATAINLTSTK
LDATAINLTSTKOR = lambda x: x | DATAINLTSTK
DATAINRTSTK = 0x0200
LDATAINRTSTKAND = lambda x: x & DATAINRTSTK
LDATAINRTSTKOR = lambda x: x | DATAINRTSTK
DATAINHAT = 0x0400
LDATAINHATAND = lambda x: x & DATAINHAT
LDATAINHATOR = lambda x: x | DATAINHAT
DATAFILEDEFAULTS = 0x0800
LDATAFILEDEFAULTSAND = lambda x: x & DATAFILEDEFAULTS
LDATAFILEDEFAULTSOR = lambda x: x | DATAFILEDEFAULTS
DATAPROFILEDEFAULTS = 0x1000
LDATAPROFILEDEFAULTSAND = lambda x: x & DATAPROFILEDEFAULTS
LDATAPROFILEDEFAULTSOR = lambda x: x | DATAPROFILEDEFAULTS
DATATICKDELAY = 0x2000
LDATATICKDELAYAND = lambda x: x & DATATICKDELAY
LDATATICKDELAYOR = lambda x: x | DATATICKDELAY


DATATYPEFLAGSNAMES = \
	{
		DATANONE: "DATANONE",
		DATAINBTN: "DATAINBTN",
		DATAOUTABS: "DATAOUTABS",
		DATAINREL: "DATAINREL",
		DATATICKS: "DATATICKS",
		DATAREPEAT: "DATAREPEAT",
		DATAOUTNORM: "DATAOUTNORM",
		DATAOUTSPECIAL: "DATAOUTSPECIAL",
		DATAADD: "DATAADD",
		DATAINLTSTK: "DATAINLTSTK",
		DATAINRTSTK: "DATAINRTSTK",
		DATAINHAT: "DATAINHAT",
		DATAFILEDEFAULTS: "DATAFILEDEFAULTS",
		DATAPROFILEDEFAULTS: "DATAPROFILEDEFAULTS",
	}

DATATYPEDESCRIPTIONS = \
	{
		DATANONE: "no data filled in this entry",
		DATAINBTN: "data in btn",
		DATAOUTABS: "data out abs",
		DATAINREL: "data in rel",
		DATATICKS: "data ticks",
		DATAREPEAT: "data repeat",
		DATAOUTNORM: "data out norm",
		DATAOUTSPECIAL: "data [out] special",
		DATAADD: "additional data dict is used",
		DATAINLTSTK: "data in lt stk",
		DATAINRTSTK: "data in rt stk",
		DATAINHAT: "data in hat",
		DATAFILEDEFAULTS: "additional data dict is used",
		DATAPROFILEDEFAULTS: "",
	}


# profile operations data types don't forget to update the lists here and
PODATAABS = 0
PODATAKEYS = PODATAABS + 1
PODATALTSTK = PODATAKEYS + 1
PODATARTSTK = PODATALTSTK + 1
PODATAHAT = PODATARTSTK + 1
PODATASPCL = PODATAHAT + 1
PODATATOTAL = PODATASPCL + 1

PROFILEOPERATIONSDATATYPESNAMES = \
	{
		PODATAABS: "PODATAABS",
		PODATAKEYS: "PODATAKEYS",
		PODATALTSTK: "PODATALTSTK",
		PODATARTSTK: "PODATARTSTK",
		PODATAHAT: "PODATAHAT",
		PODATASPCL: "PODATASPCL",
		PODATATOTAL: "PODATATOTAL",
	}


PROFILEOPERATIONSDATATYPESDESCRIPTIONS = \
	{
		PODATAABS: "PODATAABS",
		PODATAKEYS: "PODATAKEYS",
		PODATALTSTK: "PODATALTSTK",
		PODATARTSTK: "PODATARTSTK",
		PODATAHAT: "PODATAHAT",
		PODATASPCL: "PODATASPCL",
		PODATATOTAL: "PODATATOTAL",
	}


# combo data flags don't forget to update lists
DATAINBTNOUT = DATAINBTN + DATAOUTNORM
LDATAINBTNOUTAND = lambda x: x & DATAINBTNOUT
DATAINLTSTKOUT = DATAOUTABS + DATAINLTSTK
LDATAINLTSTKOUTAND = lambda x: x & DATAINLTSTKOUT
DATAINRTSTKOUT = DATAOUTABS + DATAINRTSTK
LDATAINRTSTKOUTAND = lambda x: x & DATAINRTSTKOUT
DATAINHATOUT = DATAINHAT + DATAOUTABS
LDATAINHATOUTAND = lambda x: x & DATAINHATOUT
DATAINBTNHATOUT = DATAINHAT + DATAINBTN + DATAOUTABS
LDATAINBTNHATOUTAND = lambda x: x & DATAINBTNHATOUT
DATAINLTSTKOUTRPTTICK = DATAINLTSTKOUT + DATAREPEAT + DATATICKS
DATAINRTSTKOUTRPT = DATAINRTSTKOUT + DATAREPEAT
DATAINHATOUTRPTTICKS = DATAINHATOUT + DATAREPEAT + DATATICKS
DATAINBTNHATOUTRPTTICKS = DATAINBTNHATOUT + DATAREPEAT + DATATICKS


COMBOSNAMES = \
	{
		DATAINBTNOUT: "DATAINBTNOUT",
		DATAINLTSTKOUT: "DATAINLTSTKOUT",
		DATAINRTSTKOUT: "DATAINRTSTKOUT",
		DATAINHATOUT: "DATAINHATOUT",
		DATAINBTNHATOUT: "DATAINBTNHATOUT",
		DATAINLTSTKOUTRPTTICK: "DATAINLTSTKOUTRPTTICK",
		DATAINRTSTKOUTRPT: "DATAINRTSTKOUTRPT",
		DATAINHATOUTRPTTICKS: "DATAINHATOUTRPTTICKS",
		DATAINBTNHATOUTRPTTICKS: "DATAINBTNHATOUTRPTTICKS",
	}


COMBOSDESCRIPTIONS = \
	{
		DATAINBTNOUT: "DATAINBTNOUT",
		DATAINLTSTKOUT: "DATAINLTSTKOUT",
		DATAINRTSTKOUT: "DATAINRTSTKOUT",
		DATAINHATOUT: "DATAINHATOUT",
		DATAINBTNHATOUT: "DATAINBTNHATOUT",
		DATAINLTSTKOUTRPTTICK: "DATAINLTSTKOUTRPTTICK",
		DATAINRTSTKOUTRPT: "DATAINRTSTKOUTRPT",
		DATAINHATOUTRPTTICKS: "DATAINHATOUTRPTTICKS",
		DATAINBTNHATOUTRPTTICKS: "DATAINBTNHATOUTRPTTICKS",
	}


# special types
SPPROFILEINC = 0x0001
SPPROFILEDEC = 0x0002
SPPROFILESET = 0x0004
SPREPEATLOCK = 0x0008
SPLOADPROFILES = 0x0010

SPECIALTYPESNAMES = \
	{
		SPPROFILEINC: "SPPROFILEINC",
		SPPROFILEDEC: "SPPROFILEDEC",
		SPPROFILESET: "SPPROFILESET",
		SPREPEATLOCK: "SPREPEATLOCK",
		SPLOADPROFILES: "SPLOADPROFILES",
	}

SPECIALTYPESNAMES = \
	{
		SPPROFILEINC: "profile increment",
		SPPROFILEDEC: "profile decrement",
		SPPROFILESET: "set myProfileIndex arb (unimp)",
		SPREPEATLOCK: "repeat lock (unimp)",
		SPLOADPROFILES: "load a new profile file (unimp)",
	}


# ABS EVENT DIRECTIONS ldru
DIRUP = 0b0001
LDIRUPOR = lambda x: x | DIRUP
DIRUPRT = 0b0011
LDIRUPRTOR = lambda x: x | DIRUPRT
DIRRT = 0b0010
LDIRRTOR = lambda x: x | DIRRT
DIRDNRT = 0b0110
LDIRDNRTOR = lambda x: x | DIRDNRT
DIRDN = 0b0100
LDIRDNOR = lambda x: x | DIRDN
DIRDNLT = 0b1100
LDIRDNLTOR = lambda x: x | DIRDNLT
DIRLT = 0b1000
LDIRLTOR = lambda x: x | DIRLT
DIRUPLT = 0b1001
LDIRUPLTOR = lambda x: x | DIRUPLT

ABSEVENTDIRECTIONSNAMES = \
	{
		DIRUP: "up",
		DIRUPRT: "up right",
		DIRRT: "right",
		DIRDNRT: "down right",
		DIRDN: "down",
		DIRDNLT: "down left",
		DIRLT: "left",
		DIRUPLT: "up left",
	}

# ABS EVENT DIRECTION MASKS
DIRUPMSK = 0b1110
LDIRUPMSKAND = lambda x: x & DIRUPMSK
DIRLTMSK = 0b1101
LDIRLTMSKAND = lambda x: x & DIRLTMSK
DIRUPLTMSK = 0b1100
LDIRUPLTMSKAND = lambda x: x & DIRUPLTMSK
DIRDNMSK = 0b1011
LDIRDNMSKAND = lambda x: x & DIRDNMSK
DIRDNLTMSK = 0b1001
LDIRDNLTMSKAND = lambda x: x & DIRDNLTMSK
DIRRTMSK = 0b0111
LDIRRTMSKAND = lambda x: x & DIRRTMSK
DIRUPRTMSK = 0b0110
LDIRUPRTMSKAND = lambda x: x & DIRUPRTMSK
DIRDNRTMSK = 0b0011
LDIRDNRTMSKAND = lambda x: x & DIRDNRTMSK
DIRXMSK = 0b0101
LDIRXMSKAND = lambda x: x & DIRXMSK
DIRYMSK = 0b1010
LDIRYMSKAND = lambda x: x & DIRYMSK
ABSEVENTDIRECTIONSMASKSNAMES = \
	{
		DIRUPMSK: "DIRUPMSK",
		DIRLTMSK: "DIRLTMSK",
		DIRUPLTMSK: "DIRUPLTMSK",
		DIRDNMSK: "DIRDNMSK",
		DIRDNLTMSK: "DIRDNLTMSK",
		DIRRTMSK: "DIRRTMSK",
		DIRUPRTMSK: "DIRUPRTMSK",
		DIRDNRTMSK: "DIRDNRTMSK",
		DIRXMSK: "DIRXMSK",
		DIRYMSK: "DIRYMSK",
	}

# POSITIONS OF THE DIRECTIONS IN THE LIST/STRINGS
DIRCHRUP = 0
DIRCHRRT = 1
DIRCHRDN = 2
DIRCHRLT = 3

DIRECTIONLISTNAMES = \
	{
		DIRCHRUP: "DIRCHRUP",
		DIRCHRRT: "DIRCHRRT",
		DIRCHRDN: "DIRCHRDN",
		DIRCHRLT: "DIRCHRLT",
	}

SYNREPORT = IE(LD.EV_SYN.SYN_REPORT, 0)

# GPM events
GPMDIALUP = IE(LD.EV_REL.REL_DIAL, RELUP)
GPMDIALDN = IE(LD.EV_REL.REL_DIAL, RELDOWN)
GPMDIALPRS = IE(LD.EV_KEY.BTN_0, KEYPRS)
GPMDIALHLD = IE(LD.EV_KEY.BTN_0, KEYHLD)
GPMDIALRLS = IE(LD.EV_KEY.BTN_0, KEYRLS)

# most joysticks don't support held keys, they are included for completeness, this code sets them up appropriately
# before storing the event in myCurrentEvents
ABSHATUP = IE(LD.EV_ABS.ABS_HAT0Y, ABSEVENTMIN)
ABSHATDN = IE(LD.EV_ABS.ABS_HAT0Y, ABSEVENTMAX)
ABSHATLT = IE(LD.EV_ABS.ABS_HAT0X, ABSEVENTMIN)
ABSHATRT = IE(LD.EV_ABS.ABS_HAT0X, ABSEVENTMAX)
ABSHAT0 = IE(LD.EV_ABS.ABS_HAT0X, ABSEVENT0)
ABSHATXCD = LD.EV_ABS.ABS_HAT0X
ABSHATYCD = LD.EV_ABS.ABS_HAT0Y

ABSLTSTKUP = IE(LD.EV_ABS.ABS_Y, ABSEVENTMIN)
ABSLTSTKDN = IE(LD.EV_ABS.ABS_Y, ABSEVENTMAX)
ABSLTSTKLT = IE(LD.EV_ABS.ABS_X, ABSEVENTMIN)
ABSLTSTKRT = IE(LD.EV_ABS.ABS_X, ABSEVENTMAX)
ABSLTXSTK0 = IE(LD.EV_ABS.ABS_X, ABSEVENT0)
ABSLTYSTK0 = IE(LD.EV_ABS.ABS_Y, ABSEVENT0)
ABSLTSTKXCD = LD.EV_ABS.ABS_X
ABSLTSTKYCD = LD.EV_ABS.ABS_Y

ABSRTSTKUP = IE(LD.EV_ABS.ABS_RZ, ABSEVENTMIN)
ABSRTSTKDN = IE(LD.EV_ABS.ABS_RZ, ABSEVENTMAX)
ABSRTSTKLT = IE(LD.EV_ABS.ABS_Z, ABSEVENTMIN)
ABSRTSTKRT = IE(LD.EV_ABS.ABS_Z, ABSEVENTMAX)
ABSRTSTKX0 = IE(LD.EV_ABS.ABS_Z, ABSEVENT0)
ABSRTSTKY0 = IE(LD.EV_ABS.ABS_RZ, ABSEVENT0)
ABSRTSTKXCD = LD.EV_ABS.ABS_Z
ABSRTSTKYCD = LD.EV_ABS.ABS_RZ

BTN1HLD = IE(LD.EV_KEY.BTN_SOUTH, KEYHLD)
BTN1CD = LD.EV_KEY.BTN_SOUTH
BTN1PRS = IE(LD.EV_KEY.BTN_SOUTH, KEYPRS)
BTN1RLS = IE(LD.EV_KEY.BTN_SOUTH, KEYRLS)

BTN2HLD = IE(LD.EV_KEY.BTN_EAST, KEYHLD)
BTN2CD = LD.EV_KEY.BTN_EAST
BTN2PRS = IE(LD.EV_KEY.BTN_EAST, KEYPRS)
BTN2RLS = IE(LD.EV_KEY.BTN_EAST, KEYRLS)

BTN3HLD = IE(LD.EV_KEY.BTN_C, KEYHLD)
BTN3CD = LD.EV_KEY.BTN_C
BTN3PRS = IE(LD.EV_KEY.BTN_C, KEYPRS)
BTN3RLS = IE(LD.EV_KEY.BTN_C, KEYRLS)

BTN4HLD = IE(LD.EV_KEY.BTN_NORTH, KEYHLD)
BTN4CD = LD.EV_KEY.BTN_NORTH
BTN4PRS = IE(LD.EV_KEY.BTN_NORTH, KEYPRS)
BTN4RLS = IE(LD.EV_KEY.BTN_NORTH, KEYRLS)

BTN5HLD = IE(LD.EV_KEY.BTN_WEST, KEYHLD)
BTN5CD = LD.EV_KEY.BTN_WEST
BTN5PRS = IE(LD.EV_KEY.BTN_WEST, KEYPRS)
BTN5RLS = IE(LD.EV_KEY.BTN_WEST, KEYRLS)

BTN6HLD = IE(LD.EV_KEY.BTN_Z, KEYHLD)
BTN6CD = LD.EV_KEY.BTN_Z
BTN6PRS = IE(LD.EV_KEY.BTN_Z, KEYPRS)
BTN6RLS = IE(LD.EV_KEY.BTN_Z, KEYRLS)

BTN7HLD = IE(LD.EV_KEY.BTN_TL, KEYHLD)
BTN7CD = LD.EV_KEY.BTN_TL
BTN7PRS = IE(LD.EV_KEY.BTN_TL, KEYPRS)
BTN7RLS = IE(LD.EV_KEY.BTN_TL, KEYRLS)

BTN8HLD = IE(LD.EV_KEY.BTN_TR, KEYHLD)
BTN8CD = LD.EV_KEY.BTN_TR
BTN8PRS = IE(LD.EV_KEY.BTN_TR, KEYPRS)
BTN8RLS = IE(LD.EV_KEY.BTN_TR, KEYRLS)

BTN9HLD = IE(LD.EV_KEY.BTN_TL2, KEYHLD)
BTN9CD = LD.EV_KEY.BTN_TL2
BTN9PRS = IE(LD.EV_KEY.BTN_TL2, KEYPRS)
BTN9RLS = IE(LD.EV_KEY.BTN_TL2, KEYRLS)

BTNAHLD = IE(LD.EV_KEY.BTN_TR2, KEYHLD)
BTNACD = LD.EV_KEY.BTN_TR2
BTNAPRS = IE(LD.EV_KEY.BTN_TR2, KEYPRS)
BTNARLS = IE(LD.EV_KEY.BTN_TR2, KEYRLS)

BTNBHLD = IE(LD.EV_KEY.BTN_SELECT, KEYHLD)
BTNBCD = LD.EV_KEY.BTN_SELECT
BTNBPRS = IE(LD.EV_KEY.BTN_SELECT, KEYPRS)
BTNBRLS = IE(LD.EV_KEY.BTN_SELECT, KEYRLS)

BTNCHLD = IE(LD.EV_KEY.BTN_START, KEYHLD)
BTNCCD = LD.EV_KEY.BTN_START
BTNCPRS = IE(LD.EV_KEY.BTN_START, KEYPRS)
BTNCRLS = IE(LD.EV_KEY.BTN_START, KEYRLS)

BTNDHLD = IE(LD.EV_KEY.BTN_MODE, KEYHLD)
BTNDCD = LD.EV_KEY.BTN_MODE
BTNDPRS = IE(LD.EV_KEY.BTN_MODE, KEYPRS)
BTNDRLS = IE(LD.EV_KEY.BTN_MODE, KEYRLS)

STKEVENTSLIST = [ABSLTSTKXCD, ABSLTSTKYCD, ABSRTSTKXCD, ABSRTSTKYCD]
LTSTKEVENTSLIST = [ABSLTSTKXCD, ABSLTSTKYCD]
RTSTKEVENTSLIST = [ABSRTSTKXCD, ABSRTSTKYCD]
HATEVENTSLIST = [ABSHATXCD, ABSHATYCD]
BTNEVENTSLIST = [BTN1CD, BTN2CD, BTN3CD, BTN4CD, BTN5CD, BTN6CD, BTN7CD, BTN8CD, BTN9CD,
                  BTNACD, BTNBCD, BTNCCD, BTNDCD]

#  most mice don't have a held value for the buttons,
#  it is included here for completeness,
#  and faked for use when it does happen
MSEUPFULLEVENT = [IE(LD.EV_REL.REL_Y, -MOUSEDISTANCE), SYNREPORT]
MSEDNFULLEVENT = [IE(LD.EV_REL.REL_Y, MOUSEDISTANCE), SYNREPORT]
MSELTFULLEVENT = [IE(LD.EV_REL.REL_X, -MOUSEDISTANCE), SYNREPORT]
MSERTFULLEVENT = [IE(LD.EV_REL.REL_X, MOUSEDISTANCE), SYNREPORT]

MSEWHLUPFULLEVENT = [IE(LD.EV_REL.REL_WHEEL, WHEELDISTANCE), SYNREPORT]
MSEWHLDNFULLEVENT = [IE(LD.EV_REL.REL_WHEEL, -WHEELDISTANCE), SYNREPORT]
MSEWHLLTFULLEVENT = [IE(LD.EV_REL.REL_HWHEEL, -WHEELDISTANCE), SYNREPORT]
MSEWHLRTFULLEVENT = [IE(LD.EV_REL.REL_HWHEEL, WHEELDISTANCE), SYNREPORT]

MSEXTRBTNHLDEVENT = IE(LD.EV_KEY.BTN_EXTRA, KEYHLD)
MSEXTRBTNPRSDEVENT = IE(LD.EV_KEY.BTN_EXTRA, KEYPRS)
MSEXTRBTNPRSHLDDEVENT = IE(LD.EV_KEY.BTN_EXTRA, KEYPRSHLD)
MSEXTRBTNRLSEVENT = IE(LD.EV_KEY.BTN_EXTRA, KEYRLS)
MSEXTRBTMFULLEVENT = \
	[
		MSEXTRBTNPRSHLDDEVENT,
		SYNREPORT,
		MSEXTRBTNRLSEVENT,
		SYNREPORT,
	]

MSELTBTNHLDEVENT = IE(LD.EV_KEY.BTN_LEFT, KEYHLD)
MSELTBTNPRSHLDEVENT = IE(LD.EV_KEY.BTN_LEFT, KEYPRSHLD)
MSELTBTNPRSEVENT = IE(LD.EV_KEY.BTN_LEFT, KEYPRS)
MSELTBTNRLSEVENT = IE(LD.EV_KEY.BTN_LEFT, KEYRLS)
MSELTBTNFULLEVENT = \
	[
		MSELTBTNPRSHLDEVENT,
		SYNREPORT,
		MSELTBTNRLSEVENT,
		SYNREPORT
	]

MSEMIDBTNHLDEVENT = IE(LD.EV_KEY.BTN_MIDDLE, KEYHLD)
MSEMIDBTNPRSEVENT = IE(LD.EV_KEY.BTN_MIDDLE, KEYPRS)
MSEMIDBTNPRSHLDEVENT = IE(LD.EV_KEY.BTN_MIDDLE, KEYPRSHLD)
MSEMIDBTNRLSEVENT = IE(LD.EV_KEY.BTN_MIDDLE, KEYRLS)
MSEMIDBTNFULLEVENT = \
	[
		MSEMIDBTNPRSHLDEVENT,
		SYNREPORT,
		MSEMIDBTNPRSEVENT,
		SYNREPORT,
	]

MSERTBTNHLDEVENT = IE(LD.EV_KEY.BTN_RIGHT, KEYHLD)
MSERTBTNPRSEVENT = IE(LD.EV_KEY.BTN_RIGHT, KEYPRS)
MSERTBTNPRSHLDEVENT = IE(LD.EV_KEY.BTN_RIGHT, KEYPRSHLD)
MSERTBTNRLSEVENT = IE(LD.EV_KEY.BTN_RIGHT, KEYRLS)
MSERTBTNFULLEVENT = \
	[
		MSERTBTNPRSHLDEVENT,
		SYNREPORT,
		MSERTBTNRLSEVENT,
		SYNREPORT,
	]

MSESDBTNHLDEVENT = IE(LD.EV_KEY.BTN_SIDE, KEYHLD)
MSESDBTNPSEVENT = IE(LD.EV_KEY.BTN_SIDE, KEYPRS)
MSESDBTNPRSHLDEVENT = IE(LD.EV_KEY.BTN_SIDE, KEYPRSHLD)
MSESDBTNRLSEVENT = IE(LD.EV_KEY.BTN_SIDE, KEYRLS)
MSESDBTNFULLEVENT = \
	[
		MSESDBTNPRSHLDEVENT,
		SYNREPORT,
		MSESDBTNRLSEVENT,
		SYNREPORT,
	]

# I generally do my own held key tracking as some keyboards don't support them, and sending them is less than effective,
# so think of these as reserved for possible future use
KBD0HLD = IE(LD.EV_KEY.KEY_0, KEYHLD)
KBD0PRS = IE(LD.EV_KEY.KEY_0, KEYPRS)
KBD0RLS = IE(LD.EV_KEY.KEY_0, KEYRLS)

KBD102HLD = IE(LD.EV_KEY.KEY_102ND, KEYHLD)
KBD102PRS = IE(LD.EV_KEY.KEY_102ND, KEYPRS)
KBD102RLS = IE(LD.EV_KEY.KEY_102ND, KEYRLS)

KBD1HLD = IE(LD.EV_KEY.KEY_1, KEYHLD)
KBD1PRS = IE(LD.EV_KEY.KEY_1, KEYPRS)
KBD1RLS = IE(LD.EV_KEY.KEY_1, KEYRLS)

KBD2HLD = IE(LD.EV_KEY.KEY_2, KEYHLD)
KBD2PRS = IE(LD.EV_KEY.KEY_2, KEYPRS)
KBD2RLS = IE(LD.EV_KEY.KEY_2, KEYRLS)

KBD3HLD = IE(LD.EV_KEY.KEY_3, KEYHLD)
KBD3PRS = IE(LD.EV_KEY.KEY_3, KEYPRS)
KBD3RLS = IE(LD.EV_KEY.KEY_3, KEYRLS)

KBD4HLD = IE(LD.EV_KEY.KEY_4, KEYHLD)
KBD4PRS = IE(LD.EV_KEY.KEY_4, KEYPRS)
KBD4RLS = IE(LD.EV_KEY.KEY_4, KEYRLS)

KBD5HLD = IE(LD.EV_KEY.KEY_5, KEYHLD)
KBD5PRS = IE(LD.EV_KEY.KEY_5, KEYPRS)
KBD5RLS = IE(LD.EV_KEY.KEY_5, KEYRLS)

KBD6HLD = IE(LD.EV_KEY.KEY_6, KEYHLD)
KBD6PRS = IE(LD.EV_KEY.KEY_6, KEYPRS)
KBD6RLS = IE(LD.EV_KEY.KEY_6, KEYRLS)

KBD7HLD = IE(LD.EV_KEY.KEY_7, KEYHLD)
KBD7PRS = IE(LD.EV_KEY.KEY_7, KEYPRS)
KBD7RLS = IE(LD.EV_KEY.KEY_7, KEYRLS)

KBD8HLD = IE(LD.EV_KEY.KEY_8, KEYHLD)
KBD8PRS = IE(LD.EV_KEY.KEY_8, KEYPRS)
KBD8RLS = IE(LD.EV_KEY.KEY_8, KEYRLS)

KBD9HLD = IE(LD.EV_KEY.KEY_9, KEYHLD)
KBD9PRS = IE(LD.EV_KEY.KEY_9, KEYPRS)
KBD9RLS = IE(LD.EV_KEY.KEY_9, KEYRLS)

KBDAHLD = IE(LD.EV_KEY.KEY_A, KEYHLD)
KBDAPRS = IE(LD.EV_KEY.KEY_A, KEYPRS)
KBDARLS = IE(LD.EV_KEY.KEY_A, KEYRLS)

KBDAGAINHLD = IE(LD.EV_KEY.KEY_AGAIN, KEYHLD)
KBDAGAINPRS = IE(LD.EV_KEY.KEY_AGAIN, KEYPRS)
KBDAGAINRLS = IE(LD.EV_KEY.KEY_AGAIN, KEYRLS)

KBDALTLHLD = IE(LD.EV_KEY.KEY_LEFTALT, KEYHLD)
KBDALTLPRS = IE(LD.EV_KEY.KEY_LEFTALT, KEYPRS)
KBDALTLRLS = IE(LD.EV_KEY.KEY_LEFTALT, KEYRLS)

KBDAPOSTOPHEHLD = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYHLD)
KBDAPOSTOPHEPRS = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYPRS)
KBDAPOSTOPHERLS = IE(LD.EV_KEY.KEY_APOSTROPHE, KEYRLS)

KBDBHLD = IE(LD.EV_KEY.KEY_B, KEYHLD)
KBDBPRS = IE(LD.EV_KEY.KEY_B, KEYPRS)
KBDBRLS = IE(LD.EV_KEY.KEY_B, KEYRLS)

KBDBKHLD = IE(LD.EV_KEY.KEY_BACK, KEYHLD)
KBDBKPRS = IE(LD.EV_KEY.KEY_BACK, KEYPRS)
KBDBKRLS = IE(LD.EV_KEY.KEY_BACK, KEYRLS)

KBDBKSLASHHLD = IE(LD.EV_KEY.KEY_BACKSLASH, KEYHLD)
KBDBKSLASHRRESSED = IE(LD.EV_KEY.KEY_BACKSLASH, KEYRLS)
KBDBKSLASHPELEASED = IE(LD.EV_KEY.KEY_BACKSLASH, KEYPRS)

KBDBKSPCHLD = IE(LD.EV_KEY.KEY_BACKSPACE, KEYHLD)
KBDBKSPCPRS = IE(LD.EV_KEY.KEY_BACKSPACE, KEYPRS)
KBDBKSPCRLS = IE(LD.EV_KEY.KEY_BACKSPACE, KEYRLS)

KBDCALCHLD = IE(LD.EV_KEY.KEY_CALC, KEYHLD)
KBDCALCPRS = IE(LD.EV_KEY.KEY_CALC, KEYPRS)
KBDCALCRLS = IE(LD.EV_KEY.KEY_CALC, KEYRLS)

KBDCAPSLKHLD = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYHLD)
KBDCAPSLKPRS = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYPRS)
KBDCAPSLKRLS = IE(LD.EV_KEY.KEY_CAPSLOCK, KEYRLS)

KBDCHLD = IE(LD.EV_KEY.KEY_C, KEYHLD)
KBDCPRS = IE(LD.EV_KEY.KEY_C, KEYPRS)
KBDCRLS = IE(LD.EV_KEY.KEY_C, KEYRLS)

KBDCOFFEEHLD = IE(LD.EV_KEY.KEY_COFFEE, KEYHLD)
KBDCOFFEEPRS = IE(LD.EV_KEY.KEY_COFFEE, KEYPRS)
KBDCOFFEERLS = IE(LD.EV_KEY.KEY_COFFEE, KEYRLS)

KBDCOMMAHLD = IE(LD.EV_KEY.KEY_COMMA, KEYHLD)
KBDCOMMAPRS = IE(LD.EV_KEY.KEY_COMMA, KEYPRS)
KBDCOMMARLS = IE(LD.EV_KEY.KEY_COMMA, KEYRLS)

KBDCOMPOSEHLD = IE(LD.EV_KEY.KEY_COMPOSE, KEYHLD)
KBDCOMPOSEPRS = IE(LD.EV_KEY.KEY_COMPOSE, KEYPRS)
KBDCOMPOSERLS = IE(LD.EV_KEY.KEY_COMPOSE, KEYRLS)

KBDCOPYHLD = IE(LD.EV_KEY.KEY_COPY, KEYHLD)
KBDCOPYPRS = IE(LD.EV_KEY.KEY_COPY, KEYPRS)
KBDCOPYRLS = IE(LD.EV_KEY.KEY_COPY, KEYRLS)

KBDCUTHLD = IE(LD.EV_KEY.KEY_CUT, KEYHLD)
KBDCUTPRS = IE(LD.EV_KEY.KEY_CUT, KEYPRS)
KBDCUTRLS = IE(LD.EV_KEY.KEY_CUT, KEYRLS)

KBDDHLD = IE(LD.EV_KEY.KEY_D, KEYHLD)
KBDDPRS = IE(LD.EV_KEY.KEY_D, KEYPRS)
KBDDRLS = IE(LD.EV_KEY.KEY_D, KEYRLS)

KBDDELHLD = IE(LD.EV_KEY.KEY_DELETE, KEYHLD)
KBDDELPRS = IE(LD.EV_KEY.KEY_DELETE, KEYPRS)
KBDDELRLS = IE(LD.EV_KEY.KEY_DELETE, KEYRLS)

KBDDOTHLD = IE(LD.EV_KEY.KEY_DOT, KEYHLD)
KBDDOTPRS = IE(LD.EV_KEY.KEY_DOT, KEYPRS)
KBDDOTRLS = IE(LD.EV_KEY.KEY_DOT, KEYRLS)

KBDDNHLD = IE(LD.EV_KEY.KEY_DOWN, KEYHLD)
KBDDNPRS = IE(LD.EV_KEY.KEY_DOWN, KEYPRS)
KBDDNRLS = IE(LD.EV_KEY.KEY_DOWN, KEYRLS)

KBDEHLD = IE(LD.EV_KEY.KEY_E, KEYHLD)
KBDEPRS = IE(LD.EV_KEY.KEY_E, KEYPRS)
KBDERLS = IE(LD.EV_KEY.KEY_E, KEYRLS)

KBDEDITHLD = IE(LD.EV_KEY.KEY_EDIT, KEYHLD)
KBDEDITPRS = IE(LD.EV_KEY.KEY_EDIT, KEYPRS)
KBDEDITRLS = IE(LD.EV_KEY.KEY_EDIT, KEYRLS)

KBDEJECTCDHLD = IE(LD.EV_KEY.KEY_EJECTCD, KEYHLD)
KBDEJECTCDPRS = IE(LD.EV_KEY.KEY_EJECTCD, KEYPRS)
KBDEJECTCDRLS = IE(LD.EV_KEY.KEY_EJECTCD, KEYRLS)

KBDENDHLD = IE(LD.EV_KEY.KEY_END, KEYHLD)
KBDENDPRS = IE(LD.EV_KEY.KEY_END, KEYPRS)
KBDENDRLS = IE(LD.EV_KEY.KEY_END, KEYRLS)

KBDENTERHLD = IE(LD.EV_KEY.KEY_ENTER, KEYHLD)
KBDENTERPRS = IE(LD.EV_KEY.KEY_ENTER, KEYPRS)
KBDENTERRLS = IE(LD.EV_KEY.KEY_ENTER, KEYRLS)

KBDEQHLD = IE(LD.EV_KEY.KEY_EQUAL, KEYHLD)
KBDEQPRS = IE(LD.EV_KEY.KEY_EQUAL, KEYPRS)
KBDEQRLS = IE(LD.EV_KEY.KEY_EQUAL, KEYRLS)

KBDESCHLD = IE(LD.EV_KEY.KEY_ESC, KEYHLD)
KBDESCPRS = IE(LD.EV_KEY.KEY_ESC, KEYPRS)
KBDESCRLS = IE(LD.EV_KEY.KEY_ESC, KEYRLS)

KBDF1HLD = IE(LD.EV_KEY.KEY_F1, KEYHLD)
KBDF1PRS = IE(LD.EV_KEY.KEY_F1, KEYPRS)
KBDF1RLS = IE(LD.EV_KEY.KEY_F1, KEYRLS)

KBDF2HLD = IE(LD.EV_KEY.KEY_F2, KEYHLD)
KBDF2PRS = IE(LD.EV_KEY.KEY_F2, KEYPRS)
KBDF2RLS = IE(LD.EV_KEY.KEY_F2, KEYRLS)

KBDF3HLD = IE(LD.EV_KEY.KEY_F3, KEYHLD)
KBDF3PRS = IE(LD.EV_KEY.KEY_F3, KEYPRS)
KBDF3RLS = IE(LD.EV_KEY.KEY_F3, KEYRLS)

KBDF4HLD = IE(LD.EV_KEY.KEY_F4, KEYHLD)
KBDF4PRS = IE(LD.EV_KEY.KEY_F4, KEYPRS)
KBDF4RLS = IE(LD.EV_KEY.KEY_F4, KEYRLS)

KBDF5HLD = IE(LD.EV_KEY.KEY_F5, KEYHLD)
KBDF5PRS = IE(LD.EV_KEY.KEY_F5, KEYPRS)
KBDF5RLS = IE(LD.EV_KEY.KEY_F5, KEYRLS)

KBDF6HLD = IE(LD.EV_KEY.KEY_F6, KEYHLD)
KBDF6PRS = IE(LD.EV_KEY.KEY_F6, KEYPRS)
KBDF6RLS = IE(LD.EV_KEY.KEY_F6, KEYRLS)

KBDF7HLD = IE(LD.EV_KEY.KEY_F7, KEYHLD)
KBDF7PRS = IE(LD.EV_KEY.KEY_F7, KEYPRS)
KBDF7RLS = IE(LD.EV_KEY.KEY_F7, KEYRLS)

KBDF8HLD = IE(LD.EV_KEY.KEY_F8, KEYHLD)
KBDF8PRS = IE(LD.EV_KEY.KEY_F8, KEYPRS)
KBDF8RLS = IE(LD.EV_KEY.KEY_F8, KEYRLS)

KBDF9HLD = IE(LD.EV_KEY.KEY_F9, KEYHLD)
KBDF9PRS = IE(LD.EV_KEY.KEY_F9, KEYPRS)
KBDF9RLS = IE(LD.EV_KEY.KEY_F9, KEYRLS)

KBDF10HLD = IE(LD.EV_KEY.KEY_F10, KEYHLD)
KBDF10PRS = IE(LD.EV_KEY.KEY_F10, KEYPRS)
KBDF10RLS = IE(LD.EV_KEY.KEY_F10, KEYRLS)

KBDF11HLD = IE(LD.EV_KEY.KEY_F11, KEYHLD)
KBDF11PRS = IE(LD.EV_KEY.KEY_F11, KEYPRS)
KBDF11RLS = IE(LD.EV_KEY.KEY_F11, KEYRLS)

KBDF12HLD = IE(LD.EV_KEY.KEY_F12, KEYHLD)
KBDF12PRS = IE(LD.EV_KEY.KEY_F12, KEYPRS)
KBDF12RLS = IE(LD.EV_KEY.KEY_F12, KEYRLS)

KBDF13HLD = IE(LD.EV_KEY.KEY_F13, KEYHLD)
KBDF13PRS = IE(LD.EV_KEY.KEY_F13, KEYPRS)
KBDF13RLS = IE(LD.EV_KEY.KEY_F13, KEYRLS)

KBDF14HLD = IE(LD.EV_KEY.KEY_F14, KEYHLD)
KBDF14PRS = IE(LD.EV_KEY.KEY_F14, KEYPRS)
KBDF14RLS = IE(LD.EV_KEY.KEY_F14, KEYRLS)

KBDF15HLD = IE(LD.EV_KEY.KEY_F15, KEYHLD)
KBDF15PRS = IE(LD.EV_KEY.KEY_F15, KEYPRS)
KBDF15RLS = IE(LD.EV_KEY.KEY_F15, KEYRLS)

KBDF16HLD = IE(LD.EV_KEY.KEY_F16, KEYHLD)
KBDF16PRS = IE(LD.EV_KEY.KEY_F16, KEYPRS)
KBDF16RLS = IE(LD.EV_KEY.KEY_F16, KEYRLS)

KBDF17HLD = IE(LD.EV_KEY.KEY_F17, KEYHLD)
KBDF17PRS = IE(LD.EV_KEY.KEY_F17, KEYPRS)
KBDF17RLS = IE(LD.EV_KEY.KEY_F17, KEYRLS)

KBDF18HLD = IE(LD.EV_KEY.KEY_F18, KEYHLD)
KBDF18PRS = IE(LD.EV_KEY.KEY_F18, KEYPRS)
KBDF18RLS = IE(LD.EV_KEY.KEY_F18, KEYRLS)

KBDF19HLD = IE(LD.EV_KEY.KEY_F19, KEYHLD)
KBDF19PRS = IE(LD.EV_KEY.KEY_F19, KEYPRS)
KBDF19RLS = IE(LD.EV_KEY.KEY_F19, KEYRLS)

KBDF20HLD = IE(LD.EV_KEY.KEY_F20, KEYHLD)
KBDF20PRS = IE(LD.EV_KEY.KEY_F20, KEYPRS)
KBDF20RLS = IE(LD.EV_KEY.KEY_F20, KEYRLS)

KBDF21HLD = IE(LD.EV_KEY.KEY_F21, KEYHLD)
KBDF21PRS = IE(LD.EV_KEY.KEY_F21, KEYPRS)
KBDF21RLS = IE(LD.EV_KEY.KEY_F21, KEYRLS)

KBDF22HLD = IE(LD.EV_KEY.KEY_F22, KEYHLD)
KBDF22PRS = IE(LD.EV_KEY.KEY_F22, KEYPRS)
KBDF22RLS = IE(LD.EV_KEY.KEY_F22, KEYRLS)

KBDF23HLD = IE(LD.EV_KEY.KEY_F23, KEYHLD)
KBDF23PRS = IE(LD.EV_KEY.KEY_F23, KEYPRS)
KBDF23RLS = IE(LD.EV_KEY.KEY_F23, KEYRLS)

KBDF24HLD = IE(LD.EV_KEY.KEY_F24, KEYHLD)
KBDF24PRS = IE(LD.EV_KEY.KEY_F24, KEYPRS)
KBDF24RLS = IE(LD.EV_KEY.KEY_F24, KEYRLS)

KBDFHLD = IE(LD.EV_KEY.KEY_F, KEYHLD)
KBDFPRS = IE(LD.EV_KEY.KEY_F, KEYPRS)
KBDFRLS = IE(LD.EV_KEY.KEY_F, KEYRLS)

KBDFINDHLD = IE(LD.EV_KEY.KEY_FIND, KEYHLD)
KBDFINDPRS = IE(LD.EV_KEY.KEY_FIND, KEYPRS)
KBDFINDRLS = IE(LD.EV_KEY.KEY_FIND, KEYRLS)

KBDFORWARDHLD = IE(LD.EV_KEY.KEY_FORWARD, KEYHLD)
KBDFORWARDPRS = IE(LD.EV_KEY.KEY_FORWARD, KEYPRS)
KBDFORWARDRLS = IE(LD.EV_KEY.KEY_FORWARD, KEYRLS)

KBDFRONTHLD = IE(LD.EV_KEY.KEY_FRONT, KEYHLD)
KBDFRONTPRS = IE(LD.EV_KEY.KEY_FRONT, KEYPRS)
KBDFRONTRLS = IE(LD.EV_KEY.KEY_FRONT, KEYRLS)

KBDGHLD = IE(LD.EV_KEY.KEY_G, KEYHLD)
KBDGPRS = IE(LD.EV_KEY.KEY_G, KEYPRS)
KBDGRLS = IE(LD.EV_KEY.KEY_G, KEYRLS)

KBDGRAVEHLD = IE(LD.EV_KEY.KEY_GRAVE, KEYHLD)
KBDGRAVEPRS = IE(LD.EV_KEY.KEY_GRAVE, KEYPRS)
KBDGRAVERLS = IE(LD.EV_KEY.KEY_GRAVE, KEYRLS)

KBDHANGUELHLD = IE(LD.EV_KEY.KEY_HANGEUL, KEYHLD)
KBDHANGUELPRS = IE(LD.EV_KEY.KEY_HANGEUL, KEYPRS)
KBDHANGUELRLS = IE(LD.EV_KEY.KEY_HANGEUL, KEYRLS)

KBDHANJAHLD = IE(LD.EV_KEY.KEY_HANJA, KEYHLD)
KBDHANJAPRS = IE(LD.EV_KEY.KEY_HANJA, KEYPRS)
KBDHANJARLS = IE(LD.EV_KEY.KEY_HANJA, KEYRLS)

KBDHELPHLD = IE(LD.EV_KEY.KEY_HELP, KEYHLD)
KBDHELPPRS = IE(LD.EV_KEY.KEY_HELP, KEYPRS)
KBDHELPRLS = IE(LD.EV_KEY.KEY_HELP, KEYRLS)

KBDHENKANHLD = IE(LD.EV_KEY.KEY_HENKAN, KEYHLD)
KBDHENKANPRS = IE(LD.EV_KEY.KEY_HENKAN, KEYPRS)
KBDHENKANRLS = IE(LD.EV_KEY.KEY_HENKAN, KEYRLS)

KBDHHLD = IE(LD.EV_KEY.KEY_H, KEYHLD)
KBDHPRS = IE(LD.EV_KEY.KEY_H, KEYPRS)
KBDHRLS = IE(LD.EV_KEY.KEY_H, KEYRLS)

KBDHIRAGANAHLD = IE(LD.EV_KEY.KEY_HIRAGANA, KEYHLD)
KBDHIRAGANAPRS = IE(LD.EV_KEY.KEY_HIRAGANA, KEYPRS)
KBDHIRAGANARLS = IE(LD.EV_KEY.KEY_HIRAGANA, KEYRLS)

KBDHOMEHLD = IE(LD.EV_KEY.KEY_HOME, KEYHLD)
KBDHOMEPRS = IE(LD.EV_KEY.KEY_HOME, KEYPRS)
KBDHOMERLS = IE(LD.EV_KEY.KEY_HOME, KEYRLS)

KBDIHLD = IE(LD.EV_KEY.KEY_I, KEYHLD)
KBDIPRS = IE(LD.EV_KEY.KEY_I, KEYPRS)
KBDIRLS = IE(LD.EV_KEY.KEY_I, KEYRLS)

KBDINSERTHLD = IE(LD.EV_KEY.KEY_INSERT, KEYHLD)
KBDINSERTPRS = IE(LD.EV_KEY.KEY_INSERT, KEYPRS)
KBDINSERTRLS = IE(LD.EV_KEY.KEY_INSERT, KEYRLS)

KBDJHLD = IE(LD.EV_KEY.KEY_J, KEYHLD)
KBDJPRS = IE(LD.EV_KEY.KEY_J, KEYPRS)
KBDJRLS = IE(LD.EV_KEY.KEY_J, KEYRLS)

KBDKATAKANAHLD = IE(LD.EV_KEY.KEY_KATAKANA, KEYHLD)
KBDKATAKANAPRS = IE(LD.EV_KEY.KEY_KATAKANA, KEYPRS)
KBDKATAKANARLS = IE(LD.EV_KEY.KEY_KATAKANA, KEYRLS)

KBDKATAKANAHIRAGANAHLD = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYHLD)
KBDKATAKANAHIRAGANAPRS = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYPRS)
KBDKATAKANAHIRAGANARLS = IE(LD.EV_KEY.KEY_KATAKANAHIRAGANA, KEYRLS)

KBDKHLD = IE(LD.EV_KEY.KEY_K, KEYHLD)
KBDKPRS = IE(LD.EV_KEY.KEY_K, KEYPRS)
KBDKRLS = IE(LD.EV_KEY.KEY_K, KEYRLS)

KBDKP0HLD = IE(LD.EV_KEY.KEY_KP0, KEYHLD)
KBDKP0PRS = IE(LD.EV_KEY.KEY_KP0, KEYPRS)
KBDKP0RLS = IE(LD.EV_KEY.KEY_KP0, KEYRLS)

KBDKP1HLD = IE(LD.EV_KEY.KEY_KP1, KEYHLD)
KBDKP1PRS = IE(LD.EV_KEY.KEY_KP1, KEYPRS)
KBDKP1RLS = IE(LD.EV_KEY.KEY_KP1, KEYRLS)

KBDKP2HLD = IE(LD.EV_KEY.KEY_KP2, KEYHLD)
KBDKP2PRS = IE(LD.EV_KEY.KEY_KP2, KEYPRS)
KBDKP2RLS = IE(LD.EV_KEY.KEY_KP2, KEYRLS)

KBDKP3HLD = IE(LD.EV_KEY.KEY_KP3, KEYHLD)
KBDKP3PRS = IE(LD.EV_KEY.KEY_KP3, KEYPRS)
KBDKP3RLS = IE(LD.EV_KEY.KEY_KP3, KEYRLS)

KBDKP4HLD = IE(LD.EV_KEY.KEY_KP4, KEYHLD)
KBDKP4PRS = IE(LD.EV_KEY.KEY_KP4, KEYPRS)
KBDKP4RLS = IE(LD.EV_KEY.KEY_KP4, KEYRLS)

KBDKP5HLD = IE(LD.EV_KEY.KEY_KP5, KEYHLD)
KBDKP5PRS = IE(LD.EV_KEY.KEY_KP5, KEYPRS)
KBDKP5RLS = IE(LD.EV_KEY.KEY_KP5, KEYRLS)

KBDKP6HLD = IE(LD.EV_KEY.KEY_KP6, KEYHLD)
KBDKP6PRS = IE(LD.EV_KEY.KEY_KP6, KEYPRS)
KBDKP6RLS = IE(LD.EV_KEY.KEY_KP6, KEYRLS)

KBDKP7HLD = IE(LD.EV_KEY.KEY_KP7, KEYHLD)
KBDKP7PRS = IE(LD.EV_KEY.KEY_KP7, KEYPRS)
KBDKP7RLS = IE(LD.EV_KEY.KEY_KP7, KEYRLS)

KBDKP8HLD = IE(LD.EV_KEY.KEY_KP8, KEYHLD)
KBDKP8PRS = IE(LD.EV_KEY.KEY_KP8, KEYPRS)
KBDKP8RLS = IE(LD.EV_KEY.KEY_KP8, KEYRLS)

KBDKP9HLD = IE(LD.EV_KEY.KEY_KP9, KEYHLD)
KBDKP9PRS = IE(LD.EV_KEY.KEY_KP9, KEYPRS)
KBDKP9RLS = IE(LD.EV_KEY.KEY_KP9, KEYRLS)

KBDKPCOMMAHLD = IE(LD.EV_KEY.KEY_KPCOMMA, KEYHLD)
KBDKPCOMMAPRS = IE(LD.EV_KEY.KEY_KPCOMMA, KEYPRS)
KBDKPCOMMARLS = IE(LD.EV_KEY.KEY_KPCOMMA, KEYRLS)

KBDKPDOTHLD = IE(LD.EV_KEY.KEY_KPDOT, KEYHLD)
KBDKPDOTPRS = IE(LD.EV_KEY.KEY_KPDOT, KEYPRS)
KBDKPDOTRLS = IE(LD.EV_KEY.KEY_KPDOT, KEYRLS)

KBDKPENTERHLD = IE(LD.EV_KEY.KEY_KPENTER, KEYHLD)
KBDKPENTERPRS = IE(LD.EV_KEY.KEY_KPENTER, KEYPRS)
KBDKPENTERRLS = IE(LD.EV_KEY.KEY_KPENTER, KEYRLS)

KBDKPJPCOMMAHLD = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYHLD)
KBDKPJPCOMMAPRS = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYPRS)
KBDKPJPCOMMARLS = IE(LD.EV_KEY.KEY_KPJPCOMMA, KEYRLS)

KBDKPLPARENHLD = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYHLD)
KBDKPLPARENPRS = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYPRS)
KBDKPLPARENRLS = IE(LD.EV_KEY.KEY_KPLEFTPAREN, KEYRLS)

KBDKPMINUSHLD = IE(LD.EV_KEY.KEY_KPMINUS, KEYHLD)
KBDKPMINUSPRS = IE(LD.EV_KEY.KEY_KPMINUS, KEYPRS)
KBDKPMINUSRLS = IE(LD.EV_KEY.KEY_KPMINUS, KEYRLS)

KBDKPPLUSHLD = IE(LD.EV_KEY.KEY_KPPLUS, KEYHLD)
KBDKPPLUSPRS = IE(LD.EV_KEY.KEY_KPPLUS, KEYPRS)
KBDKPPLUSRLS = IE(LD.EV_KEY.KEY_KPPLUS, KEYRLS)

KBDKPRPARENHLD = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYHLD)
KBDKPRPARENPRS = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYPRS)
KBDKPRPARENRLS = IE(LD.EV_KEY.KEY_KPRIGHTPAREN, KEYRLS)

KBDKPSLASHHLD = IE(LD.EV_KEY.KEY_KPSLASH, KEYHLD)
KBDKPSLASHPRS = IE(LD.EV_KEY.KEY_KPSLASH, KEYPRS)
KBDKPSLASHRLS = IE(LD.EV_KEY.KEY_KPSLASH, KEYRLS)

KBDKPSPLATHLD = IE(LD.EV_KEY.KEY_KPASTERISK, KEYHLD)
KBDKPSPLATPRS = IE(LD.EV_KEY.KEY_KPASTERISK, KEYPRS)
KBDKPSPLATRLS = IE(LD.EV_KEY.KEY_KPASTERISK, KEYRLS)

KBDLBRACEHLD = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYHLD)
KBDLBRACEPRS = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYPRS)
KBDLBRACERLS = IE(LD.EV_KEY.KEY_LEFTBRACE, KEYRLS)

KBDLCTRLHLD = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYHLD)
KBDLCTRLPRS = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYPRS)
KBDLCTRLRLS = IE(LD.EV_KEY.KEY_LEFTCTRL, KEYRLS)

KBDLTHLD = IE(LD.EV_KEY.KEY_LEFT, KEYHLD)
KBDLTPRS = IE(LD.EV_KEY.KEY_LEFT, KEYPRS)
KBDLTRLS = IE(LD.EV_KEY.KEY_LEFT, KEYRLS)

KBDLHLD = IE(LD.EV_KEY.KEY_L, KEYHLD)
KBDLPRS = IE(LD.EV_KEY.KEY_L, KEYPRS)
KBDLRLS = IE(LD.EV_KEY.KEY_L, KEYRLS)

KBDLMETAHLD = IE(LD.EV_KEY.KEY_LEFTMETA, KEYHLD)
KBDLMETAPRS = IE(LD.EV_KEY.KEY_LEFTMETA, KEYPRS)
KBDLMETARLS = IE(LD.EV_KEY.KEY_LEFTMETA, KEYRLS)

KBDLSHIFTHLD = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYHLD)
KBDLSHIFTPRS = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYPRS)
KBDLSHIFTRLS = IE(LD.EV_KEY.KEY_LEFTSHIFT, KEYRLS)

KBDMHLD = IE(LD.EV_KEY.KEY_M, KEYHLD)
KBDMPRS = IE(LD.EV_KEY.KEY_M, KEYPRS)
KBDMRLS = IE(LD.EV_KEY.KEY_M, KEYRLS)

KBDMINUSHLD = IE(LD.EV_KEY.KEY_MINUS, KEYHLD)
KBDMINUSPRS = IE(LD.EV_KEY.KEY_MINUS, KEYPRS)
KBDMINUSRLS = IE(LD.EV_KEY.KEY_MINUS, KEYRLS)

KBDMUHENKANHLD = IE(LD.EV_KEY.KEY_MUHENKAN, KEYHLD)
KBDMUHENKANPRS = IE(LD.EV_KEY.KEY_MUHENKAN, KEYPRS)
KBDMUHENKANRLS = IE(LD.EV_KEY.KEY_MUHENKAN, KEYRLS)

KBDMUTEHLD = IE(LD.EV_KEY.KEY_MUTE, KEYHLD)
KBDMUTEPRS = IE(LD.EV_KEY.KEY_MUTE, KEYPRS)
KBDMUTERLS = IE(LD.EV_KEY.KEY_MUTE, KEYRLS)

KBDNHLD = IE(LD.EV_KEY.KEY_N, KEYHLD)
KBDNPRS = IE(LD.EV_KEY.KEY_N, KEYPRS)
KBDNRLS = IE(LD.EV_KEY.KEY_N, KEYRLS)

KBDNEXTSONGHLD = IE(LD.EV_KEY.KEY_NEXTSONG, KEYHLD)
KBDNEXTSONGPRS = IE(LD.EV_KEY.KEY_NEXTSONG, KEYPRS)
KBDNEXTSONGRLS = IE(LD.EV_KEY.KEY_NEXTSONG, KEYRLS)

KBDNUMLKHLD = IE(LD.EV_KEY.KEY_NUMLOCK, KEYHLD)
KBDNUMLKPRS = IE(LD.EV_KEY.KEY_NUMLOCK, KEYPRS)
KBDNUMLKRLS = IE(LD.EV_KEY.KEY_NUMLOCK, KEYRLS)

KBDOHLD = IE(LD.EV_KEY.KEY_O, KEYHLD)
KBDOPRS = IE(LD.EV_KEY.KEY_O, KEYPRS)
KBDORLS = IE(LD.EV_KEY.KEY_O, KEYRLS)

KBDOPENHLD = IE(LD.EV_KEY.KEY_OPEN, KEYHLD)
KBDOPENPRS = IE(LD.EV_KEY.KEY_OPEN, KEYPRS)
KBDOPENRLS = IE(LD.EV_KEY.KEY_OPEN, KEYRLS)

KBDPASTEHLD = IE(LD.EV_KEY.KEY_PASTE, KEYHLD)
KBDPASTEPRS = IE(LD.EV_KEY.KEY_PASTE, KEYPRS)
KBDPASTERLS = IE(LD.EV_KEY.KEY_PASTE, KEYRLS)

KBDPAUSEHLD = IE(LD.EV_KEY.KEY_PAUSE, KEYHLD)
KBDPAUSEPRS = IE(LD.EV_KEY.KEY_PAUSE, KEYPRS)
KBDPAUSERLS = IE(LD.EV_KEY.KEY_PAUSE, KEYRLS)

KBDPGDNHLD = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYHLD)
KBDPGDNPRS = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYPRS)
KBDPGDNRLS = IE(LD.EV_KEY.KEY_PAGEDOWN, KEYRLS)

KBDPGUPHLD = IE(LD.EV_KEY.KEY_PAGEUP, KEYHLD)
KBDPGUPPRS = IE(LD.EV_KEY.KEY_PAGEUP, KEYPRS)
KBDPGUPRLS = IE(LD.EV_KEY.KEY_PAGEUP, KEYRLS)

KBDPHLD = IE(LD.EV_KEY.KEY_P, KEYHLD)
KBDPPRS = IE(LD.EV_KEY.KEY_P, KEYPRS)
KBDPRLS = IE(LD.EV_KEY.KEY_P, KEYRLS)

KBDPLAYPAUSEHLD = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYHLD)
KBDPLAYPAUSEPRS = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYPRS)
KBDPLAYPAUSERLS = IE(LD.EV_KEY.KEY_PLAYPAUSE, KEYRLS)

KBDPOWERHLD = IE(LD.EV_KEY.KEY_POWER, KEYHLD)
KBDPOWERPRS = IE(LD.EV_KEY.KEY_POWER, KEYPRS)
KBDPOWERRLS = IE(LD.EV_KEY.KEY_POWER, KEYRLS)

KBDPREVIOUSSONGHLD = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYHLD)
KBDPREVIOUSSONGPRS = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYPRS)
KBDPREVIOUSSONGRLS = IE(LD.EV_KEY.KEY_PREVIOUSSONG, KEYRLS)

KBDPROPSHLD = IE(LD.EV_KEY.KEY_PROPS, KEYHLD)
KBDPROPSPRS = IE(LD.EV_KEY.KEY_PROPS, KEYPRS)
KBDPROPSRLS = IE(LD.EV_KEY.KEY_PROPS, KEYRLS)

KBDQHLD = IE(LD.EV_KEY.KEY_Q, KEYHLD)
KBDQPRS = IE(LD.EV_KEY.KEY_Q, KEYPRS)
KBDQRLS = IE(LD.EV_KEY.KEY_Q, KEYRLS)

KBDRHLD = IE(LD.EV_KEY.KEY_R, KEYHLD)
KBDRPRS = IE(LD.EV_KEY.KEY_R, KEYPRS)
KBDRRLS = IE(LD.EV_KEY.KEY_R, KEYRLS)

KBDR0HLD = IE(LD.EV_KEY.KEY_RO, KEYHLD)
KBDR0PRS = IE(LD.EV_KEY.KEY_RO, KEYPRS)
KBDR0RLS = IE(LD.EV_KEY.KEY_RO, KEYRLS)

KBDRALTHLD = IE(LD.EV_KEY.KEY_RIGHTALT, KEYHLD)
KBDRALTPRS = IE(LD.EV_KEY.KEY_RIGHTALT, KEYPRS)
KBDRALTRLS = IE(LD.EV_KEY.KEY_RIGHTALT, KEYRLS)

KBDRBRACEHLD = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYHLD)
KBDRBRACEPRS = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYPRS)
KBDRBRACERLS = IE(LD.EV_KEY.KEY_RIGHTBRACE, KEYRLS)

KBDRCTRLHLD = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYHLD)
KBDRCTRLPRS = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYPRS)
KBDRCTRLRLS = IE(LD.EV_KEY.KEY_RIGHTCTRL, KEYRLS)

KBDRTHLD = IE(LD.EV_KEY.KEY_RIGHT, KEYHLD)
KBDRTPRS = IE(LD.EV_KEY.KEY_RIGHT, KEYPRS)
KBDRTRLS = IE(LD.EV_KEY.KEY_RIGHT, KEYRLS)

KBDRMETAHLD = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYHLD)
KBDRMETAPRS = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYPRS)
KBDRMETARLS = IE(LD.EV_KEY.KEY_RIGHTMETA, KEYRLS)

KBDRSHIFTHLD = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYHLD)
KBDRSHIFTPRS = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYPRS)
KBDRSHIFTRLS = IE(LD.EV_KEY.KEY_RIGHTSHIFT, KEYRLS)

KBDSCROLLDNHLD = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYHLD)
KBDSCROLLDNPRS = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYPRS)
KBDSCROLLDNRLS = IE(LD.EV_KEY.KEY_SCROLLDOWN, KEYRLS)

KBDSCROLLLKHLD = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYHLD)
KBDSCROLLLKPRS = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYPRS)
KBDSCROLLLKRLS = IE(LD.EV_KEY.KEY_SCROLLLOCK, KEYRLS)

KBDSCROLLUPHLD = IE(LD.EV_KEY.KEY_SCROLLUP, KEYHLD)
KBDSCROLLUPPRS = IE(LD.EV_KEY.KEY_SCROLLUP, KEYPRS)
KBDSCROLLUPRLS = IE(LD.EV_KEY.KEY_SCROLLUP, KEYRLS)

KBDSEMICOLONHLD = IE(LD.EV_KEY.KEY_SEMICOLON, KEYHLD)
KBDSEMICOLONPRS = IE(LD.EV_KEY.KEY_SEMICOLON, KEYPRS)
KBDSEMICOLONRLS = IE(LD.EV_KEY.KEY_SEMICOLON, KEYRLS)

KBDSHLD = IE(LD.EV_KEY.KEY_S, KEYHLD)
KBDSPRS = IE(LD.EV_KEY.KEY_S, KEYPRS)
KBDSRLS = IE(LD.EV_KEY.KEY_S, KEYRLS)

KBDSLASHHLD = IE(LD.EV_KEY.KEY_SLASH, KEYHLD)
KBDSLASHPRS = IE(LD.EV_KEY.KEY_SLASH, KEYPRS)
KBDSLASHRLS = IE(LD.EV_KEY.KEY_SLASH, KEYRLS)

KBDSLEEPHLD = IE(LD.EV_KEY.KEY_SLEEP, KEYHLD)
KBDSLEEPPRS = IE(LD.EV_KEY.KEY_SLEEP, KEYPRS)
KBDSLEEPRLS = IE(LD.EV_KEY.KEY_SLEEP, KEYRLS)

KBDSPCHLD = IE(LD.EV_KEY.KEY_SPACE, KEYHLD)
KBDSPCPRS = IE(LD.EV_KEY.KEY_SPACE, KEYPRS)
KBDSPCRLS = IE(LD.EV_KEY.KEY_SPACE, KEYRLS)

KBDSTOPCDHLD = IE(LD.EV_KEY.KEY_STOPCD, KEYHLD)
KBDSTOPCDPRS = IE(LD.EV_KEY.KEY_STOPCD, KEYPRS)
KBDSTOPCDRLS = IE(LD.EV_KEY.KEY_STOPCD, KEYRLS)

KBDSTOPHLD = IE(LD.EV_KEY.KEY_STOP, KEYHLD)
KBDSTOPPRS = IE(LD.EV_KEY.KEY_STOP, KEYPRS)
KBDSTOPRLS = IE(LD.EV_KEY.KEY_STOP, KEYRLS)

KBDSYSRQHLD = IE(LD.EV_KEY.KEY_SYSRQ, KEYHLD)
KBDSYSRQPRS = IE(LD.EV_KEY.KEY_SYSRQ, KEYPRS)
KBDSYSRQRLS = IE(LD.EV_KEY.KEY_SYSRQ, KEYRLS)

KBDTABHLD = IE(LD.EV_KEY.KEY_TAB, KEYHLD)
KBDTABPRS = IE(LD.EV_KEY.KEY_TAB, KEYPRS)
KBDTABRLS = IE(LD.EV_KEY.KEY_TAB, KEYRLS)

KBDTHLD = IE(LD.EV_KEY.KEY_T, KEYHLD)
KBDTPRS = IE(LD.EV_KEY.KEY_T, KEYPRS)
KBDTRLS = IE(LD.EV_KEY.KEY_T, KEYRLS)

KBDUHLD = IE(LD.EV_KEY.KEY_U, KEYHLD)
KBDUPRS = IE(LD.EV_KEY.KEY_U, KEYPRS)
KBDURLS = IE(LD.EV_KEY.KEY_U, KEYRLS)

KBDUNDOHLD = IE(LD.EV_KEY.KEY_UNDO, KEYHLD)
KBDUNDOPRS = IE(LD.EV_KEY.KEY_UNDO, KEYPRS)
KBDUNDORLS = IE(LD.EV_KEY.KEY_UNDO, KEYRLS)

KBDUNKNOWNHLD = IE(LD.EV_KEY.KEY_UNKNOWN, KEYHLD)
KBDUNKNOWNPRS = IE(LD.EV_KEY.KEY_UNKNOWN, KEYPRS)
KBDUNKNOWNRLS = IE(LD.EV_KEY.KEY_UNKNOWN, KEYRLS)

KBDUPHLD = IE(LD.EV_KEY.KEY_UP, KEYHLD)
KBDUPPRS = IE(LD.EV_KEY.KEY_UP, KEYPRS)
KBDUPRLS = IE(LD.EV_KEY.KEY_UP, KEYRLS)

KBDVHLD = IE(LD.EV_KEY.KEY_V, KEYHLD)
KBDVPRS = IE(LD.EV_KEY.KEY_V, KEYPRS)
KBDVRLS = IE(LD.EV_KEY.KEY_V, KEYRLS)

KBDVOLDNHLD = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYHLD)
KBDVOLDNPRS = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYPRS)
KBDVOLDNRLS = IE(LD.EV_KEY.KEY_VOLUMEDOWN, KEYRLS)

KBDVOLUPHLD = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYHLD)
KBDVOLUPPRS = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYPRS)
KBDVOLUPRLS = IE(LD.EV_KEY.KEY_VOLUMEUP, KEYRLS)

KBDWHLD = IE(LD.EV_KEY.KEY_W, KEYHLD)
KBDWPRS = IE(LD.EV_KEY.KEY_W, KEYPRS)
KBDWRLS = IE(LD.EV_KEY.KEY_W, KEYRLS)

KBDWWWHLD = IE(LD.EV_KEY.KEY_WWW, KEYHLD)
KBDWWWPRS = IE(LD.EV_KEY.KEY_WWW, KEYPRS)
KBDWWWRLS = IE(LD.EV_KEY.KEY_WWW, KEYRLS)

KBDXHLD = IE(LD.EV_KEY.KEY_X, KEYHLD)
KBDXPRS = IE(LD.EV_KEY.KEY_X, KEYPRS)
KBDXRLS = IE(LD.EV_KEY.KEY_X, KEYRLS)

KBDYENHLD = IE(LD.EV_KEY.KEY_YEN, KEYHLD)
KBDYENPRS = IE(LD.EV_KEY.KEY_YEN, KEYPRS)
KBDYENRLS = IE(LD.EV_KEY.KEY_YEN, KEYRLS)

KBDYHLD = IE(LD.EV_KEY.KEY_Y, KEYHLD)
KBDYPRS = IE(LD.EV_KEY.KEY_Y, KEYPRS)
KBDYRLS = IE(LD.EV_KEY.KEY_Y, KEYRLS)

KBDREFRESHHLD = IE(LD.EV_KEY.KEY_REFRESH, KEYHLD)
KBDREFRESHPRS = IE(LD.EV_KEY.KEY_REFRESH, KEYPRS)
KBDREFRESHRLS = IE(LD.EV_KEY.KEY_REFRESH, KEYRLS)

KBDZENKAKUHANKAKUHLD = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYHLD)
KBDZENKAKUHANKAKUPRS = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYPRS)
KBDZENKAKUHANKAKURLS = IE(LD.EV_KEY.KEY_ZENKAKUHANKAKU, KEYRLS)

KBDZHLD = IE(LD.EV_KEY.KEY_Z, KEYHLD)
KBDZPRS = IE(LD.EV_KEY.KEY_Z, KEYPRS)
KBDZRLS = IE(LD.EV_KEY.KEY_Z, KEYRLS)
KEYSYNREPORT = 0
KEYGPMDIALUP = KEYSYNREPORT + 1
KEYGPMDIALDN = KEYGPMDIALUP + 1
KEYGPMDIALPRS = KEYGPMDIALDN + 1
KEYGPMDIALHLD = KEYGPMDIALPRS + 1
KEYGPMDIALRLS = KEYGPMDIALHLD + 1

KEYABSHATUP = KEYGPMDIALRLS + 1
KEYABSHATDN = KEYABSHATUP + 1
KEYABSHATLT = KEYABSHATDN + 1
KEYABSHATRT = KEYABSHATLT + 1
KEYABSHAT0 = KEYABSHATRT + 1
KEYABSHATXCD = KEYABSHAT0 + 1
KEYABSHATYCD = KEYABSHATXCD + 1

KEYABSLTSTKUP = KEYABSHATYCD + 1
KEYABSLTSTKDN = KEYABSLTSTKUP + 1
KEYABSLTSTKLT = KEYABSLTSTKDN + 1
KEYABSLTSTKRT = KEYABSLTSTKLT + 1
KEYABSLTXSTK0 = KEYABSLTSTKRT + 1
KEYABSLTYSTK0 = KEYABSLTXSTK0 + 1
KEYABSLTSTKXCD = KEYABSLTYSTK0 + 1
KEYABSLTSTKYCD = KEYABSLTSTKXCD + 1

KEYABSRTSTKUP = KEYABSLTSTKYCD + 1
KEYABSRTSTKDN = KEYABSRTSTKUP + 1
KEYABSRTSTKLT = KEYABSRTSTKDN + 1
KEYABSRTSTKRT = KEYABSRTSTKLT + 1
KEYABSRTSTKX0 = KEYABSRTSTKRT + 1
KEYABSRTSTKY0 = KEYABSRTSTKX0 + 1
KEYABSRTSTKXCD = KEYABSRTSTKY0 + 1
KEYABSRTSTKYCD = KEYABSRTSTKXCD + 1

KEYBTN1HLD = KEYABSRTSTKYCD + 1
KEYBTN1CD = KEYBTN1HLD + 1
KEYBTN1PRS = KEYBTN1CD + 1
KEYBTN1RLS = KEYBTN1PRS + 1

KEYBTN2HLD = KEYBTN1RLS + 1
KEYBTN2CD = KEYBTN2HLD + 1
KEYBTN2PRS = KEYBTN2CD + 1
KEYBTN2RLS = KEYBTN2PRS + 1

KEYBTN3HLD = KEYBTN2RLS + 1
KEYBTN3CD = KEYBTN3HLD + 1
KEYBTN3PRS = KEYBTN3CD + 1
KEYBTN3RLS = KEYBTN3PRS + 1

KEYBTN4HLD = KEYBTN3RLS + 1
KEYBTN4CD = KEYBTN4HLD + 1
KEYBTN4PRS = KEYBTN4CD + 1
KEYBTN4RLS = KEYBTN4PRS + 1

KEYBTN5HLD = KEYBTN4RLS + 1
KEYBTN5CD = KEYBTN5HLD + 1
KEYBTN5PRS = KEYBTN5CD + 1
KEYBTN5RLS = KEYBTN5PRS + 1

KEYBTN6HLD = KEYBTN5RLS + 1
KEYBTN6CD = KEYBTN6HLD + 1
KEYBTN6PRS = KEYBTN6CD + 1
KEYBTN6RLS = KEYBTN6PRS + 1

KEYBTN7HLD = KEYBTN6RLS + 1
KEYBTN7CD = KEYBTN7HLD + 1
KEYBTN7PRS = KEYBTN7CD + 1
KEYBTN7RLS = KEYBTN7PRS + 1

KEYBTN8HLD = KEYBTN7RLS + 1
KEYBTN8CD = KEYBTN8HLD + 1
KEYBTN8PRS = KEYBTN8CD + 1
KEYBTN8RLS = KEYBTN8PRS + 1

KEYBTNLTSTKHLD = KEYBTN8RLS + 1
KEYBTNLTSTKCD = KEYBTNLTSTKHLD + 1
KEYBTNLTSTKPRS = KEYBTNLTSTKCD + 1
KEYBTNLTSTKRLS = KEYBTNLTSTKPRS + 1

KEYBTNRTSTKHLD = KEYBTNLTSTKRLS + 1
KEYBTNRTSTKCD = KEYBTNRTSTKHLD + 1
KEYBTNRTSTKPRS = KEYBTNRTSTKCD + 1
KEYBTNRTSTKRLS = KEYBTNRTSTKPRS + 1

KEYBTNLTFACEHLD = KEYBTNRTSTKRLS + 1
KEYBTNLTFACECD = KEYBTNLTFACEHLD + 1
KEYBTNLTFACEPRS = KEYBTNLTFACECD + 1
KEYBTNLTFACERLS = KEYBTNLTFACEPRS + 1

KEYBTNRTFACEHLD = KEYBTNLTFACERLS + 1
KEYBTNRTFACECD = KEYBTNRTFACEHLD + 1
KEYBTNRTFACEPRS = KEYBTNRTFACECD + 1
KEYBTNRTFACERLS = KEYBTNRTFACEPRS + 1

KEYBTNHOMEHLD = KEYBTNRTFACERLS + 1
KEYBTNHOMECD = KEYBTNHOMEHLD + 1
KEYBTNHOMEPRS = KEYBTNHOMECD + 1
KEYBTNHOMERLS = KEYBTNHOMEPRS + 1
