from time import sleep
import libevdev as LD


def IDB():
	devHBI = LD.Device()
	devHBI.name = "hot beef injector"
	devHBI.enable(LD.EV_REL.REL_X)
	devHBI.enable(LD.EV_REL.REL_Y)
	devHBI.enable(LD.EV_REL.REL_WHEEL)
	devHBI.enable(LD.EV_REL.REL_WHEEL_HI_RES)
	devHBI.enable(LD.EV_REL.REL_HWHEEL)
	devHBI.enable(LD.EV_REL.REL_HWHEEL_HI_RES)

	devHBI.enable(LD.EV_KEY.BTN_LEFT)
	devHBI.enable(LD.EV_KEY.BTN_RIGHT)
	devHBI.enable(LD.EV_KEY.BTN_MIDDLE)
	devHBI.enable(LD.EV_KEY.BTN_SIDE)
	devHBI.enable(LD.EV_KEY.BTN_EXTRA)

	devHBI.enable(LD.EV_KEY.KEY_0)
	devHBI.enable(LD.EV_KEY.KEY_1)
	devHBI.enable(LD.EV_KEY.KEY_102ND)
	devHBI.enable(LD.EV_KEY.KEY_2)
	devHBI.enable(LD.EV_KEY.KEY_3)
	devHBI.enable(LD.EV_KEY.KEY_4)
	devHBI.enable(LD.EV_KEY.KEY_5)
	devHBI.enable(LD.EV_KEY.KEY_6)
	devHBI.enable(LD.EV_KEY.KEY_7)
	devHBI.enable(LD.EV_KEY.KEY_8)
	devHBI.enable(LD.EV_KEY.KEY_9)
	devHBI.enable(LD.EV_KEY.KEY_A)
	devHBI.enable(LD.EV_KEY.KEY_AGAIN)
	devHBI.enable(LD.EV_KEY.KEY_APOSTROPHE)
	devHBI.enable(LD.EV_KEY.KEY_B)
	devHBI.enable(LD.EV_KEY.KEY_BACK)
	devHBI.enable(LD.EV_KEY.KEY_BACKSLASH)
	devHBI.enable(LD.EV_KEY.KEY_BACKSPACE)
	devHBI.enable(LD.EV_KEY.KEY_C)
	devHBI.enable(LD.EV_KEY.KEY_CALC)
	devHBI.enable(LD.EV_KEY.KEY_CAPSLOCK)
	devHBI.enable(LD.EV_KEY.KEY_COFFEE)
	devHBI.enable(LD.EV_KEY.KEY_COMMA)
	devHBI.enable(LD.EV_KEY.KEY_COMPOSE)
	devHBI.enable(LD.EV_KEY.KEY_COPY)
	devHBI.enable(LD.EV_KEY.KEY_CUT)
	devHBI.enable(LD.EV_KEY.KEY_D)
	devHBI.enable(LD.EV_KEY.KEY_DELETE)
	devHBI.enable(LD.EV_KEY.KEY_DOT)
	devHBI.enable(LD.EV_KEY.KEY_DOWN)
	devHBI.enable(LD.EV_KEY.KEY_E)
	devHBI.enable(LD.EV_KEY.KEY_EDIT)
	devHBI.enable(LD.EV_KEY.KEY_EJECTCD)
	devHBI.enable(LD.EV_KEY.KEY_END)
	devHBI.enable(LD.EV_KEY.KEY_ENTER)
	devHBI.enable(LD.EV_KEY.KEY_EQUAL)
	devHBI.enable(LD.EV_KEY.KEY_ESC)
	devHBI.enable(LD.EV_KEY.KEY_F)
	devHBI.enable(LD.EV_KEY.KEY_F1)
	devHBI.enable(LD.EV_KEY.KEY_F10)
	devHBI.enable(LD.EV_KEY.KEY_F11)
	devHBI.enable(LD.EV_KEY.KEY_F12)
	devHBI.enable(LD.EV_KEY.KEY_F13)
	devHBI.enable(LD.EV_KEY.KEY_F14)
	devHBI.enable(LD.EV_KEY.KEY_F15)
	devHBI.enable(LD.EV_KEY.KEY_F16)
	devHBI.enable(LD.EV_KEY.KEY_F17)
	devHBI.enable(LD.EV_KEY.KEY_F18)
	devHBI.enable(LD.EV_KEY.KEY_F19)
	devHBI.enable(LD.EV_KEY.KEY_F2)
	devHBI.enable(LD.EV_KEY.KEY_F20)
	devHBI.enable(LD.EV_KEY.KEY_F21)
	devHBI.enable(LD.EV_KEY.KEY_F22)
	devHBI.enable(LD.EV_KEY.KEY_F23)
	devHBI.enable(LD.EV_KEY.KEY_F24)
	devHBI.enable(LD.EV_KEY.KEY_F3)
	devHBI.enable(LD.EV_KEY.KEY_F4)
	devHBI.enable(LD.EV_KEY.KEY_F5)
	devHBI.enable(LD.EV_KEY.KEY_F6)
	devHBI.enable(LD.EV_KEY.KEY_F7)
	devHBI.enable(LD.EV_KEY.KEY_F8)
	devHBI.enable(LD.EV_KEY.KEY_F9)
	devHBI.enable(LD.EV_KEY.KEY_FIND)
	devHBI.enable(LD.EV_KEY.KEY_FORWARD)
	devHBI.enable(LD.EV_KEY.KEY_FRONT)
	devHBI.enable(LD.EV_KEY.KEY_G)
	devHBI.enable(LD.EV_KEY.KEY_GRAVE)
	devHBI.enable(LD.EV_KEY.KEY_H)
	devHBI.enable(LD.EV_KEY.KEY_HANGEUL)
	devHBI.enable(LD.EV_KEY.KEY_HANJA)
	devHBI.enable(LD.EV_KEY.KEY_HELP)
	devHBI.enable(LD.EV_KEY.KEY_HENKAN)
	devHBI.enable(LD.EV_KEY.KEY_HIRAGANA)
	devHBI.enable(LD.EV_KEY.KEY_HOME)
	devHBI.enable(LD.EV_KEY.KEY_I)
	devHBI.enable(LD.EV_KEY.KEY_INSERT)
	devHBI.enable(LD.EV_KEY.KEY_J)
	devHBI.enable(LD.EV_KEY.KEY_K)
	devHBI.enable(LD.EV_KEY.KEY_KATAKANA)
	devHBI.enable(LD.EV_KEY.KEY_KATAKANAHIRAGANA)
	devHBI.enable(LD.EV_KEY.KEY_KP0)
	devHBI.enable(LD.EV_KEY.KEY_KP1)
	devHBI.enable(LD.EV_KEY.KEY_KP2)
	devHBI.enable(LD.EV_KEY.KEY_KP3)
	devHBI.enable(LD.EV_KEY.KEY_KP4)
	devHBI.enable(LD.EV_KEY.KEY_KP5)
	devHBI.enable(LD.EV_KEY.KEY_KP6)
	devHBI.enable(LD.EV_KEY.KEY_KP7)
	devHBI.enable(LD.EV_KEY.KEY_KP8)
	devHBI.enable(LD.EV_KEY.KEY_KP9)
	devHBI.enable(LD.EV_KEY.KEY_KPASTERISK)
	devHBI.enable(LD.EV_KEY.KEY_KPCOMMA)
	devHBI.enable(LD.EV_KEY.KEY_KPDOT)
	devHBI.enable(LD.EV_KEY.KEY_KPENTER)
	devHBI.enable(LD.EV_KEY.KEY_KPEQUAL)
	devHBI.enable(LD.EV_KEY.KEY_KPJPCOMMA)
	devHBI.enable(LD.EV_KEY.KEY_KPLEFTPAREN)
	devHBI.enable(LD.EV_KEY.KEY_KPMINUS)
	devHBI.enable(LD.EV_KEY.KEY_KPPLUS)
	devHBI.enable(LD.EV_KEY.KEY_KPRIGHTPAREN)
	devHBI.enable(LD.EV_KEY.KEY_KPSLASH)
	devHBI.enable(LD.EV_KEY.KEY_L)
	devHBI.enable(LD.EV_KEY.KEY_LEFT)
	devHBI.enable(LD.EV_KEY.KEY_LEFTALT)
	devHBI.enable(LD.EV_KEY.KEY_LEFTBRACE)
	devHBI.enable(LD.EV_KEY.KEY_LEFTCTRL)
	devHBI.enable(LD.EV_KEY.KEY_LEFTMETA)
	devHBI.enable(LD.EV_KEY.KEY_LEFTSHIFT)
	devHBI.enable(LD.EV_KEY.KEY_M)
	devHBI.enable(LD.EV_KEY.KEY_MINUS)
	devHBI.enable(LD.EV_KEY.KEY_MUHENKAN)
	devHBI.enable(LD.EV_KEY.KEY_MUTE)
	devHBI.enable(LD.EV_KEY.KEY_N)
	devHBI.enable(LD.EV_KEY.KEY_NEXTSONG)
	devHBI.enable(LD.EV_KEY.KEY_NUMLOCK)
	devHBI.enable(LD.EV_KEY.KEY_O)
	devHBI.enable(LD.EV_KEY.KEY_OPEN)
	devHBI.enable(LD.EV_KEY.KEY_P)
	devHBI.enable(LD.EV_KEY.KEY_PAGEDOWN)
	devHBI.enable(LD.EV_KEY.KEY_PAGEUP)
	devHBI.enable(LD.EV_KEY.KEY_PASTE)
	devHBI.enable(LD.EV_KEY.KEY_PAUSE)
	devHBI.enable(LD.EV_KEY.KEY_PLAYPAUSE)
	devHBI.enable(LD.EV_KEY.KEY_POWER)
	devHBI.enable(LD.EV_KEY.KEY_PREVIOUSSONG)
	devHBI.enable(LD.EV_KEY.KEY_PROPS)
	devHBI.enable(LD.EV_KEY.KEY_Q)
	devHBI.enable(LD.EV_KEY.KEY_R)
	devHBI.enable(LD.EV_KEY.KEY_REFRESH)
	devHBI.enable(LD.EV_KEY.KEY_RIGHT)
	devHBI.enable(LD.EV_KEY.KEY_RIGHTALT)
	devHBI.enable(LD.EV_KEY.KEY_RIGHTBRACE)
	devHBI.enable(LD.EV_KEY.KEY_RIGHTCTRL)
	devHBI.enable(LD.EV_KEY.KEY_RIGHTMETA)
	devHBI.enable(LD.EV_KEY.KEY_RIGHTSHIFT)
	devHBI.enable(LD.EV_KEY.KEY_RO)
	devHBI.enable(LD.EV_KEY.KEY_S)
	devHBI.enable(LD.EV_KEY.KEY_SCROLLDOWN)
	devHBI.enable(LD.EV_KEY.KEY_SCROLLLOCK)
	devHBI.enable(LD.EV_KEY.KEY_SCROLLUP)
	devHBI.enable(LD.EV_KEY.KEY_SEMICOLON)
	devHBI.enable(LD.EV_KEY.KEY_SLASH)
	devHBI.enable(LD.EV_KEY.KEY_SLEEP)
	devHBI.enable(LD.EV_KEY.KEY_SPACE)
	devHBI.enable(LD.EV_KEY.KEY_STOP)
	devHBI.enable(LD.EV_KEY.KEY_STOPCD)
	devHBI.enable(LD.EV_KEY.KEY_SYSRQ)
	devHBI.enable(LD.EV_KEY.KEY_T)
	devHBI.enable(LD.EV_KEY.KEY_TAB)
	devHBI.enable(LD.EV_KEY.KEY_U)
	devHBI.enable(LD.EV_KEY.KEY_UNDO)
	devHBI.enable(LD.EV_KEY.KEY_UNKNOWN)
	devHBI.enable(LD.EV_KEY.KEY_UP)
	devHBI.enable(LD.EV_KEY.KEY_V)
	devHBI.enable(LD.EV_KEY.KEY_VOLUMEDOWN)
	devHBI.enable(LD.EV_KEY.KEY_VOLUMEUP)
	devHBI.enable(LD.EV_KEY.KEY_W)
	devHBI.enable(LD.EV_KEY.KEY_WWW)
	devHBI.enable(LD.EV_KEY.KEY_X)
	devHBI.enable(LD.EV_KEY.KEY_Y)
	devHBI.enable(LD.EV_KEY.KEY_YEN)
	devHBI.enable(LD.EV_KEY.KEY_Z)
	devHBI.enable(LD.EV_KEY.KEY_ZENKAKUHANKAKU)
	hbiDevice = devHBI.create_uinput_device()
	print("New device at {} ({})".format(hbiDevice.devnode, hbiDevice.syspath))
	sleep(1)
	return hbiDevice

# myDevHandle = doTheWork()
#
# devHBI = LD.Device()
# events = [InputEvent(LD.EV_REL.REL_X, 30),
# 					InputEvent(LD.EV_REL.REL_Y, 30),
# 					InputEvent(LD.EV_KEY.KEY_A, 1),
# 					InputEvent(LD.EV_KEY.KEY_A, 0),
# 					InputEvent(LD.EV_SYN.SYN_REPORT, 0)]
#
# myDevHandle.send_events(events)
